// Generated by tools/generate_yolo26n_top_wrapper.py
module yolo26n_sram_2r2w #(
  parameter integer ADDR_WIDTH = 1,
  parameter integer DEPTH = 1
) (
  input clock,
  input [ADDR_WIDTH-1:0] raddr0,
  input [ADDR_WIDTH-1:0] raddr1,
  input re0,
  input re1,
  output [31:0] rdata0,
  output [31:0] rdata1,
  input [ADDR_WIDTH-1:0] waddr0,
  input [ADDR_WIDTH-1:0] waddr1,
  input we0,
  input we1,
  input [31:0] wdata0,
  input [31:0] wdata1
);
  reg [31:0] mem [0:DEPTH-1];
  assign rdata0 = re0 ? mem[raddr0] : 32'h00000000;
  assign rdata1 = re1 ? mem[raddr1] : 32'h00000000;
  always @(posedge clock) begin
    if (we0) begin
      mem[waddr0] <= wdata0;
    end
    if (we1) begin
      mem[waddr1] <= wdata1;
    end
  end
endmodule
