`timescale 1ns / 1ps
// Generated by tools/generate_yolo26n_top_wrapper.py
// Behavioral top-level integration using explicit SRAM wrapper instances.
module yolo26n_top(
  input clock,
  input reset,
  input start,
  output reg done,
  output busy,
  output [4:0] current_stage,
  input host_input_we,
  input [20:0] host_input_addr,
  input [31:0] host_input_data,
  input [10:0] host_output_addr,
  output [31:0] host_output_data
);

  localparam integer STAGE_COUNT = 24;

  reg running;
  reg [4:0] active_stage;
  reg [STAGE_COUNT-1:0] stage_start;

  assign busy = running;
  assign current_stage = active_stage;
  wire stage0_active = running && (active_stage == 5'd0);
  wire stage0_done;
  wire [20:0] stage0_input_address0;
  wire [20:0] stage0_input_address1;
  wire stage0_input_ce0;
  wire stage0_input_ce1;
  wire [31:0] stage0_input_q0;
  wire [31:0] stage0_input_q1;
  wire [20:0] stage0_output_address0;
  wire [20:0] stage0_output_address1;
  wire stage0_output_ce0;
  wire stage0_output_ce1;
  wire stage0_output_we0;
  wire stage0_output_we1;
  wire [31:0] stage0_output_d0;
  wire [31:0] stage0_output_d1;

  wire stage1_active = running && (active_stage == 5'd1);
  wire stage1_done;
  wire [20:0] stage1_input_address0;
  wire [20:0] stage1_input_address1;
  wire stage1_input_ce0;
  wire stage1_input_ce1;
  wire [31:0] stage1_input_q0;
  wire [31:0] stage1_input_q1;
  wire [19:0] stage1_output_address0;
  wire [19:0] stage1_output_address1;
  wire stage1_output_ce0;
  wire stage1_output_ce1;
  wire stage1_output_we0;
  wire stage1_output_we1;
  wire [31:0] stage1_output_d0;
  wire [31:0] stage1_output_d1;

  wire stage2_active = running && (active_stage == 5'd2);
  wire stage2_done;
  wire [19:0] stage2_input0_address0;
  wire [19:0] stage2_input0_address1;
  wire stage2_input0_ce0;
  wire stage2_input0_ce1;
  wire [31:0] stage2_input0_q0;
  wire [31:0] stage2_input0_q1;
  wire [20:0] stage2_output0_address0;
  wire [20:0] stage2_output0_address1;
  wire stage2_output0_ce0;
  wire stage2_output0_ce1;
  wire stage2_output0_we0;
  wire stage2_output0_we1;
  wire [31:0] stage2_output0_d0;
  wire [31:0] stage2_output0_d1;

  wire stage3_active = running && (active_stage == 5'd3);
  wire stage3_done;
  wire [20:0] stage3_input0_address0;
  wire [20:0] stage3_input0_address1;
  wire stage3_input0_ce0;
  wire stage3_input0_ce1;
  wire [31:0] stage3_input0_q0;
  wire [31:0] stage3_input0_q1;
  wire [18:0] stage3_output0_address0;
  wire [18:0] stage3_output0_address1;
  wire stage3_output0_ce0;
  wire stage3_output0_ce1;
  wire stage3_output0_we0;
  wire stage3_output0_we1;
  wire [31:0] stage3_output0_d0;
  wire [31:0] stage3_output0_d1;

  wire stage4_active = running && (active_stage == 5'd4);
  wire stage4_done;
  wire [18:0] stage4_input0_address0;
  wire [18:0] stage4_input0_address1;
  wire stage4_input0_ce0;
  wire stage4_input0_ce1;
  wire [31:0] stage4_input0_q0;
  wire [31:0] stage4_input0_q1;
  wire [19:0] stage4_output0_address0;
  wire [19:0] stage4_output0_address1;
  wire stage4_output0_ce0;
  wire stage4_output0_ce1;
  wire stage4_output0_we0;
  wire stage4_output0_we1;
  wire [31:0] stage4_output0_d0;
  wire [31:0] stage4_output0_d1;

  wire stage5_active = running && (active_stage == 5'd5);
  wire stage5_done;
  wire [19:0] stage5_input0_address0;
  wire [19:0] stage5_input0_address1;
  wire stage5_input0_ce0;
  wire stage5_input0_ce1;
  wire [31:0] stage5_input0_q0;
  wire [31:0] stage5_input0_q1;
  wire [17:0] stage5_output0_address0;
  wire [17:0] stage5_output0_address1;
  wire stage5_output0_ce0;
  wire stage5_output0_ce1;
  wire stage5_output0_we0;
  wire stage5_output0_we1;
  wire [31:0] stage5_output0_d0;
  wire [31:0] stage5_output0_d1;

  wire stage6_active = running && (active_stage == 5'd6);
  wire stage6_done;
  wire [17:0] stage6_input0_address0;
  wire [17:0] stage6_input0_address1;
  wire stage6_input0_ce0;
  wire stage6_input0_ce1;
  wire [31:0] stage6_input0_q0;
  wire [31:0] stage6_input0_q1;
  wire [17:0] stage6_output0_address0;
  wire [17:0] stage6_output0_address1;
  wire stage6_output0_ce0;
  wire stage6_output0_ce1;
  wire stage6_output0_we0;
  wire stage6_output0_we1;
  wire [31:0] stage6_output0_d0;
  wire [31:0] stage6_output0_d1;

  wire stage7_active = running && (active_stage == 5'd7);
  wire stage7_done;
  wire [17:0] stage7_input0_address0;
  wire [17:0] stage7_input0_address1;
  wire stage7_input0_ce0;
  wire stage7_input0_ce1;
  wire [31:0] stage7_input0_q0;
  wire [31:0] stage7_input0_q1;
  wire [16:0] stage7_output0_address0;
  wire [16:0] stage7_output0_address1;
  wire stage7_output0_ce0;
  wire stage7_output0_ce1;
  wire stage7_output0_we0;
  wire stage7_output0_we1;
  wire [31:0] stage7_output0_d0;
  wire [31:0] stage7_output0_d1;

  wire stage8_active = running && (active_stage == 5'd8);
  wire stage8_done;
  wire [16:0] stage8_input0_address0;
  wire [16:0] stage8_input0_address1;
  wire stage8_input0_ce0;
  wire stage8_input0_ce1;
  wire [31:0] stage8_input0_q0;
  wire [31:0] stage8_input0_q1;
  wire [16:0] stage8_output0_address0;
  wire [16:0] stage8_output0_address1;
  wire stage8_output0_ce0;
  wire stage8_output0_ce1;
  wire stage8_output0_we0;
  wire stage8_output0_we1;
  wire [31:0] stage8_output0_d0;
  wire [31:0] stage8_output0_d1;

  wire stage9_active = running && (active_stage == 5'd9);
  wire stage9_done;
  wire [16:0] stage9_input0_address0;
  wire [16:0] stage9_input0_address1;
  wire stage9_input0_ce0;
  wire stage9_input0_ce1;
  wire [31:0] stage9_input0_q0;
  wire [31:0] stage9_input0_q1;
  wire [16:0] stage9_output0_address0;
  wire [16:0] stage9_output0_address1;
  wire stage9_output0_ce0;
  wire stage9_output0_ce1;
  wire stage9_output0_we0;
  wire stage9_output0_we1;
  wire [31:0] stage9_output0_d0;
  wire [31:0] stage9_output0_d1;

  wire stage10_active = running && (active_stage == 5'd10);
  wire stage10_done;
  wire [16:0] stage10_input0_address0;
  wire [16:0] stage10_input0_address1;
  wire stage10_input0_ce0;
  wire stage10_input0_ce1;
  wire [31:0] stage10_input0_q0;
  wire [31:0] stage10_input0_q1;
  wire [16:0] stage10_output0_address0;
  wire [16:0] stage10_output0_address1;
  wire stage10_output0_ce0;
  wire stage10_output0_ce1;
  wire stage10_output0_we0;
  wire stage10_output0_we1;
  wire [31:0] stage10_output0_d0;
  wire [31:0] stage10_output0_d1;

  wire stage11_active = running && (active_stage == 5'd11);
  wire stage11_done;
  wire [16:0] stage11_input0_address0;
  wire [16:0] stage11_input0_address1;
  wire stage11_input0_ce0;
  wire stage11_input0_ce1;
  wire [31:0] stage11_input0_q0;
  wire [31:0] stage11_input0_q1;
  wire [18:0] stage11_output0_address0;
  wire [18:0] stage11_output0_address1;
  wire stage11_output0_ce0;
  wire stage11_output0_ce1;
  wire stage11_output0_we0;
  wire stage11_output0_we1;
  wire [31:0] stage11_output0_d0;
  wire [31:0] stage11_output0_d1;

  wire stage12_active = running && (active_stage == 5'd12);
  wire stage12_done;
  wire [18:0] stage12_input0_address0;
  wire [18:0] stage12_input0_address1;
  wire stage12_input0_ce0;
  wire stage12_input0_ce1;
  wire [31:0] stage12_input0_q0;
  wire [31:0] stage12_input0_q1;
  wire [17:0] stage12_input1_address0;
  wire [17:0] stage12_input1_address1;
  wire stage12_input1_ce0;
  wire stage12_input1_ce1;
  wire [31:0] stage12_input1_q0;
  wire [31:0] stage12_input1_q1;
  wire [19:0] stage12_output0_address0;
  wire [19:0] stage12_output0_address1;
  wire stage12_output0_ce0;
  wire stage12_output0_ce1;
  wire stage12_output0_we0;
  wire stage12_output0_we1;
  wire [31:0] stage12_output0_d0;
  wire [31:0] stage12_output0_d1;

  wire stage13_active = running && (active_stage == 5'd13);
  wire stage13_done;
  wire [19:0] stage13_input0_address0;
  wire [19:0] stage13_input0_address1;
  wire stage13_input0_ce0;
  wire stage13_input0_ce1;
  wire [31:0] stage13_input0_q0;
  wire [31:0] stage13_input0_q1;
  wire [17:0] stage13_output0_address0;
  wire [17:0] stage13_output0_address1;
  wire stage13_output0_ce0;
  wire stage13_output0_ce1;
  wire stage13_output0_we0;
  wire stage13_output0_we1;
  wire [31:0] stage13_output0_d0;
  wire [31:0] stage13_output0_d1;

  wire stage14_active = running && (active_stage == 5'd14);
  wire stage14_done;
  wire [17:0] stage14_input0_address0;
  wire [17:0] stage14_input0_address1;
  wire stage14_input0_ce0;
  wire stage14_input0_ce1;
  wire [31:0] stage14_input0_q0;
  wire [31:0] stage14_input0_q1;
  wire [19:0] stage14_output0_address0;
  wire [19:0] stage14_output0_address1;
  wire stage14_output0_ce0;
  wire stage14_output0_ce1;
  wire stage14_output0_we0;
  wire stage14_output0_we1;
  wire [31:0] stage14_output0_d0;
  wire [31:0] stage14_output0_d1;

  wire stage15_active = running && (active_stage == 5'd15);
  wire stage15_done;
  wire [19:0] stage15_input0_address0;
  wire [19:0] stage15_input0_address1;
  wire stage15_input0_ce0;
  wire stage15_input0_ce1;
  wire [31:0] stage15_input0_q0;
  wire [31:0] stage15_input0_q1;
  wire [19:0] stage15_input1_address0;
  wire [19:0] stage15_input1_address1;
  wire stage15_input1_ce0;
  wire stage15_input1_ce1;
  wire [31:0] stage15_input1_q0;
  wire [31:0] stage15_input1_q1;
  wire [20:0] stage15_output0_address0;
  wire [20:0] stage15_output0_address1;
  wire stage15_output0_ce0;
  wire stage15_output0_ce1;
  wire stage15_output0_we0;
  wire stage15_output0_we1;
  wire [31:0] stage15_output0_d0;
  wire [31:0] stage15_output0_d1;

  wire stage16_active = running && (active_stage == 5'd16);
  wire stage16_done;
  wire [20:0] stage16_input0_address0;
  wire [20:0] stage16_input0_address1;
  wire stage16_input0_ce0;
  wire stage16_input0_ce1;
  wire [31:0] stage16_input0_q0;
  wire [31:0] stage16_input0_q1;
  wire [18:0] stage16_output0_address0;
  wire [18:0] stage16_output0_address1;
  wire stage16_output0_ce0;
  wire stage16_output0_ce1;
  wire stage16_output0_we0;
  wire stage16_output0_we1;
  wire [31:0] stage16_output0_d0;
  wire [31:0] stage16_output0_d1;

  wire stage17_active = running && (active_stage == 5'd17);
  wire stage17_done;
  wire [18:0] stage17_input0_address0;
  wire [18:0] stage17_input0_address1;
  wire stage17_input0_ce0;
  wire stage17_input0_ce1;
  wire [31:0] stage17_input0_q0;
  wire [31:0] stage17_input0_q1;
  wire [16:0] stage17_output0_address0;
  wire [16:0] stage17_output0_address1;
  wire stage17_output0_ce0;
  wire stage17_output0_ce1;
  wire stage17_output0_we0;
  wire stage17_output0_we1;
  wire [31:0] stage17_output0_d0;
  wire [31:0] stage17_output0_d1;

  wire stage18_active = running && (active_stage == 5'd18);
  wire stage18_done;
  wire [16:0] stage18_input0_address0;
  wire [16:0] stage18_input0_address1;
  wire stage18_input0_ce0;
  wire stage18_input0_ce1;
  wire [31:0] stage18_input0_q0;
  wire [31:0] stage18_input0_q1;
  wire [17:0] stage18_input1_address0;
  wire [17:0] stage18_input1_address1;
  wire stage18_input1_ce0;
  wire stage18_input1_ce1;
  wire [31:0] stage18_input1_q0;
  wire [31:0] stage18_input1_q1;
  wire [18:0] stage18_output0_address0;
  wire [18:0] stage18_output0_address1;
  wire stage18_output0_ce0;
  wire stage18_output0_ce1;
  wire stage18_output0_we0;
  wire stage18_output0_we1;
  wire [31:0] stage18_output0_d0;
  wire [31:0] stage18_output0_d1;

  wire stage19_active = running && (active_stage == 5'd19);
  wire stage19_done;
  wire [18:0] stage19_input0_address0;
  wire [18:0] stage19_input0_address1;
  wire stage19_input0_ce0;
  wire stage19_input0_ce1;
  wire [31:0] stage19_input0_q0;
  wire [31:0] stage19_input0_q1;
  wire [17:0] stage19_output0_address0;
  wire [17:0] stage19_output0_address1;
  wire stage19_output0_ce0;
  wire stage19_output0_ce1;
  wire stage19_output0_we0;
  wire stage19_output0_we1;
  wire [31:0] stage19_output0_d0;
  wire [31:0] stage19_output0_d1;

  wire stage20_active = running && (active_stage == 5'd20);
  wire stage20_done;
  wire [17:0] stage20_input0_address0;
  wire [17:0] stage20_input0_address1;
  wire stage20_input0_ce0;
  wire stage20_input0_ce1;
  wire [31:0] stage20_input0_q0;
  wire [31:0] stage20_input0_q1;
  wire [15:0] stage20_output0_address0;
  wire [15:0] stage20_output0_address1;
  wire stage20_output0_ce0;
  wire stage20_output0_ce1;
  wire stage20_output0_we0;
  wire stage20_output0_we1;
  wire [31:0] stage20_output0_d0;
  wire [31:0] stage20_output0_d1;

  wire stage21_active = running && (active_stage == 5'd21);
  wire stage21_done;
  wire [15:0] stage21_input0_address0;
  wire [15:0] stage21_input0_address1;
  wire stage21_input0_ce0;
  wire stage21_input0_ce1;
  wire [31:0] stage21_input0_q0;
  wire [31:0] stage21_input0_q1;
  wire [16:0] stage21_input1_address0;
  wire [16:0] stage21_input1_address1;
  wire stage21_input1_ce0;
  wire stage21_input1_ce1;
  wire [31:0] stage21_input1_q0;
  wire [31:0] stage21_input1_q1;
  wire [17:0] stage21_output0_address0;
  wire [17:0] stage21_output0_address1;
  wire stage21_output0_ce0;
  wire stage21_output0_ce1;
  wire stage21_output0_we0;
  wire stage21_output0_we1;
  wire [31:0] stage21_output0_d0;
  wire [31:0] stage21_output0_d1;

  wire stage22_active = running && (active_stage == 5'd22);
  wire stage22_done;
  wire [17:0] stage22_input0_address0;
  wire [17:0] stage22_input0_address1;
  wire stage22_input0_ce0;
  wire stage22_input0_ce1;
  wire [31:0] stage22_input0_q0;
  wire [31:0] stage22_input0_q1;
  wire [16:0] stage22_output0_address0;
  wire [16:0] stage22_output0_address1;
  wire stage22_output0_ce0;
  wire stage22_output0_ce1;
  wire stage22_output0_we0;
  wire stage22_output0_we1;
  wire [31:0] stage22_output0_d0;
  wire [31:0] stage22_output0_d1;

  wire stage23_active = running && (active_stage == 5'd23);
  wire stage23_done;
  wire [18:0] stage23_input0_address0;
  wire [18:0] stage23_input0_address1;
  wire stage23_input0_ce0;
  wire stage23_input0_ce1;
  wire [31:0] stage23_input0_q0;
  wire [31:0] stage23_input0_q1;
  wire [17:0] stage23_input1_address0;
  wire [17:0] stage23_input1_address1;
  wire stage23_input1_ce0;
  wire stage23_input1_ce1;
  wire [31:0] stage23_input1_q0;
  wire [31:0] stage23_input1_q1;
  wire [16:0] stage23_input2_address0;
  wire [16:0] stage23_input2_address1;
  wire stage23_input2_ce0;
  wire stage23_input2_ce1;
  wire [31:0] stage23_input2_q0;
  wire [31:0] stage23_input2_q1;
  wire [10:0] stage23_output0_address0;
  wire [10:0] stage23_output0_address1;
  wire stage23_output0_ce0;
  wire stage23_output0_ce1;
  wire stage23_output0_we0;
  wire stage23_output0_we1;
  wire [31:0] stage23_output0_d0;
  wire [31:0] stage23_output0_d1;

  wire [20:0] mem_images_raddr0;
  wire [20:0] mem_images_raddr1;
  wire mem_images_re0;
  wire mem_images_re1;
  wire [31:0] mem_images_rdata0;
  wire [31:0] mem_images_rdata1;
  wire [20:0] mem_images_waddr0;
  wire [20:0] mem_images_waddr1;
  wire mem_images_we0;
  wire mem_images_we1;
  wire [31:0] mem_images_wdata0;
  wire [31:0] mem_images_wdata1;
  assign mem_images_raddr0 = (stage0_active) ? stage0_input_address0 : 21'd0;
  assign mem_images_re0 = (stage0_active) ? stage0_input_ce0 : 1'b0;
  assign mem_images_raddr1 = (stage0_active) ? stage0_input_address1 : 21'd0;
  assign mem_images_re1 = (stage0_active) ? stage0_input_ce1 : 1'b0;
  assign mem_images_waddr0 = host_input_addr;
  assign mem_images_we0 = host_input_we;
  assign mem_images_wdata0 = host_input_data;
  assign mem_images_waddr1 = 21'd0;
  assign mem_images_we1 = 1'b0;
  assign mem_images_wdata1 = 32'h00000000;
  yolo26n_sram_2r2w #(.ADDR_WIDTH(21), .DEPTH(1228800)) u_mem_images (
    .clock(clock),
    .raddr0(mem_images_raddr0),
    .raddr1(mem_images_raddr1),
    .re0(mem_images_re0),
    .re1(mem_images_re1),
    .rdata0(mem_images_rdata0),
    .rdata1(mem_images_rdata1),
    .waddr0(mem_images_waddr0),
    .waddr1(mem_images_waddr1),
    .we0(mem_images_we0),
    .we1(mem_images_we1),
    .wdata0(mem_images_wdata0),
    .wdata1(mem_images_wdata1)
  );

  wire [20:0] mem_model_0_act_Mul_output_0_raddr0;
  wire [20:0] mem_model_0_act_Mul_output_0_raddr1;
  wire mem_model_0_act_Mul_output_0_re0;
  wire mem_model_0_act_Mul_output_0_re1;
  wire [31:0] mem_model_0_act_Mul_output_0_rdata0;
  wire [31:0] mem_model_0_act_Mul_output_0_rdata1;
  wire [20:0] mem_model_0_act_Mul_output_0_waddr0;
  wire [20:0] mem_model_0_act_Mul_output_0_waddr1;
  wire mem_model_0_act_Mul_output_0_we0;
  wire mem_model_0_act_Mul_output_0_we1;
  wire [31:0] mem_model_0_act_Mul_output_0_wdata0;
  wire [31:0] mem_model_0_act_Mul_output_0_wdata1;
  assign mem_model_0_act_Mul_output_0_raddr0 = (stage1_active) ? stage1_input_address0 : 21'd0;
  assign mem_model_0_act_Mul_output_0_re0 = (stage1_active) ? stage1_input_ce0 : 1'b0;
  assign mem_model_0_act_Mul_output_0_raddr1 = (stage1_active) ? stage1_input_address1 : 21'd0;
  assign mem_model_0_act_Mul_output_0_re1 = (stage1_active) ? stage1_input_ce1 : 1'b0;
  assign mem_model_0_act_Mul_output_0_waddr0 = stage0_output_address0;
  assign mem_model_0_act_Mul_output_0_we0 = stage0_active && stage0_output_ce0 && stage0_output_we0;
  assign mem_model_0_act_Mul_output_0_wdata0 = stage0_output_d0;
  assign mem_model_0_act_Mul_output_0_waddr1 = stage0_output_address1;
  assign mem_model_0_act_Mul_output_0_we1 = stage0_active && stage0_output_ce1 && stage0_output_we1;
  assign mem_model_0_act_Mul_output_0_wdata1 = stage0_output_d1;
  yolo26n_sram_2r2w #(.ADDR_WIDTH(21), .DEPTH(1638400)) u_mem_model_0_act_Mul_output_0 (
    .clock(clock),
    .raddr0(mem_model_0_act_Mul_output_0_raddr0),
    .raddr1(mem_model_0_act_Mul_output_0_raddr1),
    .re0(mem_model_0_act_Mul_output_0_re0),
    .re1(mem_model_0_act_Mul_output_0_re1),
    .rdata0(mem_model_0_act_Mul_output_0_rdata0),
    .rdata1(mem_model_0_act_Mul_output_0_rdata1),
    .waddr0(mem_model_0_act_Mul_output_0_waddr0),
    .waddr1(mem_model_0_act_Mul_output_0_waddr1),
    .we0(mem_model_0_act_Mul_output_0_we0),
    .we1(mem_model_0_act_Mul_output_0_we1),
    .wdata0(mem_model_0_act_Mul_output_0_wdata0),
    .wdata1(mem_model_0_act_Mul_output_0_wdata1)
  );

  wire [19:0] mem_model_1_act_Mul_output_0_raddr0;
  wire [19:0] mem_model_1_act_Mul_output_0_raddr1;
  wire mem_model_1_act_Mul_output_0_re0;
  wire mem_model_1_act_Mul_output_0_re1;
  wire [31:0] mem_model_1_act_Mul_output_0_rdata0;
  wire [31:0] mem_model_1_act_Mul_output_0_rdata1;
  wire [19:0] mem_model_1_act_Mul_output_0_waddr0;
  wire [19:0] mem_model_1_act_Mul_output_0_waddr1;
  wire mem_model_1_act_Mul_output_0_we0;
  wire mem_model_1_act_Mul_output_0_we1;
  wire [31:0] mem_model_1_act_Mul_output_0_wdata0;
  wire [31:0] mem_model_1_act_Mul_output_0_wdata1;
  assign mem_model_1_act_Mul_output_0_raddr0 = (stage2_active) ? stage2_input0_address0 : 20'd0;
  assign mem_model_1_act_Mul_output_0_re0 = (stage2_active) ? stage2_input0_ce0 : 1'b0;
  assign mem_model_1_act_Mul_output_0_raddr1 = (stage2_active) ? stage2_input0_address1 : 20'd0;
  assign mem_model_1_act_Mul_output_0_re1 = (stage2_active) ? stage2_input0_ce1 : 1'b0;
  assign mem_model_1_act_Mul_output_0_waddr0 = stage1_output_address0;
  assign mem_model_1_act_Mul_output_0_we0 = stage1_active && stage1_output_ce0 && stage1_output_we0;
  assign mem_model_1_act_Mul_output_0_wdata0 = stage1_output_d0;
  assign mem_model_1_act_Mul_output_0_waddr1 = stage1_output_address1;
  assign mem_model_1_act_Mul_output_0_we1 = stage1_active && stage1_output_ce1 && stage1_output_we1;
  assign mem_model_1_act_Mul_output_0_wdata1 = stage1_output_d1;
  yolo26n_sram_2r2w #(.ADDR_WIDTH(20), .DEPTH(819200)) u_mem_model_1_act_Mul_output_0 (
    .clock(clock),
    .raddr0(mem_model_1_act_Mul_output_0_raddr0),
    .raddr1(mem_model_1_act_Mul_output_0_raddr1),
    .re0(mem_model_1_act_Mul_output_0_re0),
    .re1(mem_model_1_act_Mul_output_0_re1),
    .rdata0(mem_model_1_act_Mul_output_0_rdata0),
    .rdata1(mem_model_1_act_Mul_output_0_rdata1),
    .waddr0(mem_model_1_act_Mul_output_0_waddr0),
    .waddr1(mem_model_1_act_Mul_output_0_waddr1),
    .we0(mem_model_1_act_Mul_output_0_we0),
    .we1(mem_model_1_act_Mul_output_0_we1),
    .wdata0(mem_model_1_act_Mul_output_0_wdata0),
    .wdata1(mem_model_1_act_Mul_output_0_wdata1)
  );

  wire [20:0] mem_model_2_cv2_act_Mul_output_0_raddr0;
  wire [20:0] mem_model_2_cv2_act_Mul_output_0_raddr1;
  wire mem_model_2_cv2_act_Mul_output_0_re0;
  wire mem_model_2_cv2_act_Mul_output_0_re1;
  wire [31:0] mem_model_2_cv2_act_Mul_output_0_rdata0;
  wire [31:0] mem_model_2_cv2_act_Mul_output_0_rdata1;
  wire [20:0] mem_model_2_cv2_act_Mul_output_0_waddr0;
  wire [20:0] mem_model_2_cv2_act_Mul_output_0_waddr1;
  wire mem_model_2_cv2_act_Mul_output_0_we0;
  wire mem_model_2_cv2_act_Mul_output_0_we1;
  wire [31:0] mem_model_2_cv2_act_Mul_output_0_wdata0;
  wire [31:0] mem_model_2_cv2_act_Mul_output_0_wdata1;
  assign mem_model_2_cv2_act_Mul_output_0_raddr0 = (stage3_active) ? stage3_input0_address0 : 21'd0;
  assign mem_model_2_cv2_act_Mul_output_0_re0 = (stage3_active) ? stage3_input0_ce0 : 1'b0;
  assign mem_model_2_cv2_act_Mul_output_0_raddr1 = (stage3_active) ? stage3_input0_address1 : 21'd0;
  assign mem_model_2_cv2_act_Mul_output_0_re1 = (stage3_active) ? stage3_input0_ce1 : 1'b0;
  assign mem_model_2_cv2_act_Mul_output_0_waddr0 = stage2_output0_address0;
  assign mem_model_2_cv2_act_Mul_output_0_we0 = stage2_active && stage2_output0_ce0 && stage2_output0_we0;
  assign mem_model_2_cv2_act_Mul_output_0_wdata0 = stage2_output0_d0;
  assign mem_model_2_cv2_act_Mul_output_0_waddr1 = stage2_output0_address1;
  assign mem_model_2_cv2_act_Mul_output_0_we1 = stage2_active && stage2_output0_ce1 && stage2_output0_we1;
  assign mem_model_2_cv2_act_Mul_output_0_wdata1 = stage2_output0_d1;
  yolo26n_sram_2r2w #(.ADDR_WIDTH(21), .DEPTH(1638400)) u_mem_model_2_cv2_act_Mul_output_0 (
    .clock(clock),
    .raddr0(mem_model_2_cv2_act_Mul_output_0_raddr0),
    .raddr1(mem_model_2_cv2_act_Mul_output_0_raddr1),
    .re0(mem_model_2_cv2_act_Mul_output_0_re0),
    .re1(mem_model_2_cv2_act_Mul_output_0_re1),
    .rdata0(mem_model_2_cv2_act_Mul_output_0_rdata0),
    .rdata1(mem_model_2_cv2_act_Mul_output_0_rdata1),
    .waddr0(mem_model_2_cv2_act_Mul_output_0_waddr0),
    .waddr1(mem_model_2_cv2_act_Mul_output_0_waddr1),
    .we0(mem_model_2_cv2_act_Mul_output_0_we0),
    .we1(mem_model_2_cv2_act_Mul_output_0_we1),
    .wdata0(mem_model_2_cv2_act_Mul_output_0_wdata0),
    .wdata1(mem_model_2_cv2_act_Mul_output_0_wdata1)
  );

  wire [18:0] mem_model_3_act_Mul_output_0_raddr0;
  wire [18:0] mem_model_3_act_Mul_output_0_raddr1;
  wire mem_model_3_act_Mul_output_0_re0;
  wire mem_model_3_act_Mul_output_0_re1;
  wire [31:0] mem_model_3_act_Mul_output_0_rdata0;
  wire [31:0] mem_model_3_act_Mul_output_0_rdata1;
  wire [18:0] mem_model_3_act_Mul_output_0_waddr0;
  wire [18:0] mem_model_3_act_Mul_output_0_waddr1;
  wire mem_model_3_act_Mul_output_0_we0;
  wire mem_model_3_act_Mul_output_0_we1;
  wire [31:0] mem_model_3_act_Mul_output_0_wdata0;
  wire [31:0] mem_model_3_act_Mul_output_0_wdata1;
  assign mem_model_3_act_Mul_output_0_raddr0 = (stage4_active) ? stage4_input0_address0 : 19'd0;
  assign mem_model_3_act_Mul_output_0_re0 = (stage4_active) ? stage4_input0_ce0 : 1'b0;
  assign mem_model_3_act_Mul_output_0_raddr1 = (stage4_active) ? stage4_input0_address1 : 19'd0;
  assign mem_model_3_act_Mul_output_0_re1 = (stage4_active) ? stage4_input0_ce1 : 1'b0;
  assign mem_model_3_act_Mul_output_0_waddr0 = stage3_output0_address0;
  assign mem_model_3_act_Mul_output_0_we0 = stage3_active && stage3_output0_ce0 && stage3_output0_we0;
  assign mem_model_3_act_Mul_output_0_wdata0 = stage3_output0_d0;
  assign mem_model_3_act_Mul_output_0_waddr1 = stage3_output0_address1;
  assign mem_model_3_act_Mul_output_0_we1 = stage3_active && stage3_output0_ce1 && stage3_output0_we1;
  assign mem_model_3_act_Mul_output_0_wdata1 = stage3_output0_d1;
  yolo26n_sram_2r2w #(.ADDR_WIDTH(19), .DEPTH(409600)) u_mem_model_3_act_Mul_output_0 (
    .clock(clock),
    .raddr0(mem_model_3_act_Mul_output_0_raddr0),
    .raddr1(mem_model_3_act_Mul_output_0_raddr1),
    .re0(mem_model_3_act_Mul_output_0_re0),
    .re1(mem_model_3_act_Mul_output_0_re1),
    .rdata0(mem_model_3_act_Mul_output_0_rdata0),
    .rdata1(mem_model_3_act_Mul_output_0_rdata1),
    .waddr0(mem_model_3_act_Mul_output_0_waddr0),
    .waddr1(mem_model_3_act_Mul_output_0_waddr1),
    .we0(mem_model_3_act_Mul_output_0_we0),
    .we1(mem_model_3_act_Mul_output_0_we1),
    .wdata0(mem_model_3_act_Mul_output_0_wdata0),
    .wdata1(mem_model_3_act_Mul_output_0_wdata1)
  );

  wire [19:0] mem_model_4_cv2_act_Mul_output_0_raddr0;
  wire [19:0] mem_model_4_cv2_act_Mul_output_0_raddr1;
  wire mem_model_4_cv2_act_Mul_output_0_re0;
  wire mem_model_4_cv2_act_Mul_output_0_re1;
  wire [31:0] mem_model_4_cv2_act_Mul_output_0_rdata0;
  wire [31:0] mem_model_4_cv2_act_Mul_output_0_rdata1;
  wire [19:0] mem_model_4_cv2_act_Mul_output_0_waddr0;
  wire [19:0] mem_model_4_cv2_act_Mul_output_0_waddr1;
  wire mem_model_4_cv2_act_Mul_output_0_we0;
  wire mem_model_4_cv2_act_Mul_output_0_we1;
  wire [31:0] mem_model_4_cv2_act_Mul_output_0_wdata0;
  wire [31:0] mem_model_4_cv2_act_Mul_output_0_wdata1;
  assign mem_model_4_cv2_act_Mul_output_0_raddr0 = (stage5_active) ? stage5_input0_address0 : (stage15_active) ? stage15_input1_address0 : 20'd0;
  assign mem_model_4_cv2_act_Mul_output_0_re0 = (stage5_active) ? stage5_input0_ce0 : (stage15_active) ? stage15_input1_ce0 : 1'b0;
  assign mem_model_4_cv2_act_Mul_output_0_raddr1 = (stage5_active) ? stage5_input0_address1 : (stage15_active) ? stage15_input1_address1 : 20'd0;
  assign mem_model_4_cv2_act_Mul_output_0_re1 = (stage5_active) ? stage5_input0_ce1 : (stage15_active) ? stage15_input1_ce1 : 1'b0;
  assign mem_model_4_cv2_act_Mul_output_0_waddr0 = stage4_output0_address0;
  assign mem_model_4_cv2_act_Mul_output_0_we0 = stage4_active && stage4_output0_ce0 && stage4_output0_we0;
  assign mem_model_4_cv2_act_Mul_output_0_wdata0 = stage4_output0_d0;
  assign mem_model_4_cv2_act_Mul_output_0_waddr1 = stage4_output0_address1;
  assign mem_model_4_cv2_act_Mul_output_0_we1 = stage4_active && stage4_output0_ce1 && stage4_output0_we1;
  assign mem_model_4_cv2_act_Mul_output_0_wdata1 = stage4_output0_d1;
  yolo26n_sram_2r2w #(.ADDR_WIDTH(20), .DEPTH(819200)) u_mem_model_4_cv2_act_Mul_output_0 (
    .clock(clock),
    .raddr0(mem_model_4_cv2_act_Mul_output_0_raddr0),
    .raddr1(mem_model_4_cv2_act_Mul_output_0_raddr1),
    .re0(mem_model_4_cv2_act_Mul_output_0_re0),
    .re1(mem_model_4_cv2_act_Mul_output_0_re1),
    .rdata0(mem_model_4_cv2_act_Mul_output_0_rdata0),
    .rdata1(mem_model_4_cv2_act_Mul_output_0_rdata1),
    .waddr0(mem_model_4_cv2_act_Mul_output_0_waddr0),
    .waddr1(mem_model_4_cv2_act_Mul_output_0_waddr1),
    .we0(mem_model_4_cv2_act_Mul_output_0_we0),
    .we1(mem_model_4_cv2_act_Mul_output_0_we1),
    .wdata0(mem_model_4_cv2_act_Mul_output_0_wdata0),
    .wdata1(mem_model_4_cv2_act_Mul_output_0_wdata1)
  );

  wire [17:0] mem_model_5_act_Mul_output_0_raddr0;
  wire [17:0] mem_model_5_act_Mul_output_0_raddr1;
  wire mem_model_5_act_Mul_output_0_re0;
  wire mem_model_5_act_Mul_output_0_re1;
  wire [31:0] mem_model_5_act_Mul_output_0_rdata0;
  wire [31:0] mem_model_5_act_Mul_output_0_rdata1;
  wire [17:0] mem_model_5_act_Mul_output_0_waddr0;
  wire [17:0] mem_model_5_act_Mul_output_0_waddr1;
  wire mem_model_5_act_Mul_output_0_we0;
  wire mem_model_5_act_Mul_output_0_we1;
  wire [31:0] mem_model_5_act_Mul_output_0_wdata0;
  wire [31:0] mem_model_5_act_Mul_output_0_wdata1;
  assign mem_model_5_act_Mul_output_0_raddr0 = (stage6_active) ? stage6_input0_address0 : 18'd0;
  assign mem_model_5_act_Mul_output_0_re0 = (stage6_active) ? stage6_input0_ce0 : 1'b0;
  assign mem_model_5_act_Mul_output_0_raddr1 = (stage6_active) ? stage6_input0_address1 : 18'd0;
  assign mem_model_5_act_Mul_output_0_re1 = (stage6_active) ? stage6_input0_ce1 : 1'b0;
  assign mem_model_5_act_Mul_output_0_waddr0 = stage5_output0_address0;
  assign mem_model_5_act_Mul_output_0_we0 = stage5_active && stage5_output0_ce0 && stage5_output0_we0;
  assign mem_model_5_act_Mul_output_0_wdata0 = stage5_output0_d0;
  assign mem_model_5_act_Mul_output_0_waddr1 = stage5_output0_address1;
  assign mem_model_5_act_Mul_output_0_we1 = stage5_active && stage5_output0_ce1 && stage5_output0_we1;
  assign mem_model_5_act_Mul_output_0_wdata1 = stage5_output0_d1;
  yolo26n_sram_2r2w #(.ADDR_WIDTH(18), .DEPTH(204800)) u_mem_model_5_act_Mul_output_0 (
    .clock(clock),
    .raddr0(mem_model_5_act_Mul_output_0_raddr0),
    .raddr1(mem_model_5_act_Mul_output_0_raddr1),
    .re0(mem_model_5_act_Mul_output_0_re0),
    .re1(mem_model_5_act_Mul_output_0_re1),
    .rdata0(mem_model_5_act_Mul_output_0_rdata0),
    .rdata1(mem_model_5_act_Mul_output_0_rdata1),
    .waddr0(mem_model_5_act_Mul_output_0_waddr0),
    .waddr1(mem_model_5_act_Mul_output_0_waddr1),
    .we0(mem_model_5_act_Mul_output_0_we0),
    .we1(mem_model_5_act_Mul_output_0_we1),
    .wdata0(mem_model_5_act_Mul_output_0_wdata0),
    .wdata1(mem_model_5_act_Mul_output_0_wdata1)
  );

  wire [17:0] mem_model_6_cv2_act_Mul_output_0_raddr0;
  wire [17:0] mem_model_6_cv2_act_Mul_output_0_raddr1;
  wire mem_model_6_cv2_act_Mul_output_0_re0;
  wire mem_model_6_cv2_act_Mul_output_0_re1;
  wire [31:0] mem_model_6_cv2_act_Mul_output_0_rdata0;
  wire [31:0] mem_model_6_cv2_act_Mul_output_0_rdata1;
  wire [17:0] mem_model_6_cv2_act_Mul_output_0_waddr0;
  wire [17:0] mem_model_6_cv2_act_Mul_output_0_waddr1;
  wire mem_model_6_cv2_act_Mul_output_0_we0;
  wire mem_model_6_cv2_act_Mul_output_0_we1;
  wire [31:0] mem_model_6_cv2_act_Mul_output_0_wdata0;
  wire [31:0] mem_model_6_cv2_act_Mul_output_0_wdata1;
  assign mem_model_6_cv2_act_Mul_output_0_raddr0 = (stage7_active) ? stage7_input0_address0 : (stage12_active) ? stage12_input1_address0 : 18'd0;
  assign mem_model_6_cv2_act_Mul_output_0_re0 = (stage7_active) ? stage7_input0_ce0 : (stage12_active) ? stage12_input1_ce0 : 1'b0;
  assign mem_model_6_cv2_act_Mul_output_0_raddr1 = (stage7_active) ? stage7_input0_address1 : (stage12_active) ? stage12_input1_address1 : 18'd0;
  assign mem_model_6_cv2_act_Mul_output_0_re1 = (stage7_active) ? stage7_input0_ce1 : (stage12_active) ? stage12_input1_ce1 : 1'b0;
  assign mem_model_6_cv2_act_Mul_output_0_waddr0 = stage6_output0_address0;
  assign mem_model_6_cv2_act_Mul_output_0_we0 = stage6_active && stage6_output0_ce0 && stage6_output0_we0;
  assign mem_model_6_cv2_act_Mul_output_0_wdata0 = stage6_output0_d0;
  assign mem_model_6_cv2_act_Mul_output_0_waddr1 = stage6_output0_address1;
  assign mem_model_6_cv2_act_Mul_output_0_we1 = stage6_active && stage6_output0_ce1 && stage6_output0_we1;
  assign mem_model_6_cv2_act_Mul_output_0_wdata1 = stage6_output0_d1;
  yolo26n_sram_2r2w #(.ADDR_WIDTH(18), .DEPTH(204800)) u_mem_model_6_cv2_act_Mul_output_0 (
    .clock(clock),
    .raddr0(mem_model_6_cv2_act_Mul_output_0_raddr0),
    .raddr1(mem_model_6_cv2_act_Mul_output_0_raddr1),
    .re0(mem_model_6_cv2_act_Mul_output_0_re0),
    .re1(mem_model_6_cv2_act_Mul_output_0_re1),
    .rdata0(mem_model_6_cv2_act_Mul_output_0_rdata0),
    .rdata1(mem_model_6_cv2_act_Mul_output_0_rdata1),
    .waddr0(mem_model_6_cv2_act_Mul_output_0_waddr0),
    .waddr1(mem_model_6_cv2_act_Mul_output_0_waddr1),
    .we0(mem_model_6_cv2_act_Mul_output_0_we0),
    .we1(mem_model_6_cv2_act_Mul_output_0_we1),
    .wdata0(mem_model_6_cv2_act_Mul_output_0_wdata0),
    .wdata1(mem_model_6_cv2_act_Mul_output_0_wdata1)
  );

  wire [16:0] mem_model_7_act_Mul_output_0_raddr0;
  wire [16:0] mem_model_7_act_Mul_output_0_raddr1;
  wire mem_model_7_act_Mul_output_0_re0;
  wire mem_model_7_act_Mul_output_0_re1;
  wire [31:0] mem_model_7_act_Mul_output_0_rdata0;
  wire [31:0] mem_model_7_act_Mul_output_0_rdata1;
  wire [16:0] mem_model_7_act_Mul_output_0_waddr0;
  wire [16:0] mem_model_7_act_Mul_output_0_waddr1;
  wire mem_model_7_act_Mul_output_0_we0;
  wire mem_model_7_act_Mul_output_0_we1;
  wire [31:0] mem_model_7_act_Mul_output_0_wdata0;
  wire [31:0] mem_model_7_act_Mul_output_0_wdata1;
  assign mem_model_7_act_Mul_output_0_raddr0 = (stage8_active) ? stage8_input0_address0 : 17'd0;
  assign mem_model_7_act_Mul_output_0_re0 = (stage8_active) ? stage8_input0_ce0 : 1'b0;
  assign mem_model_7_act_Mul_output_0_raddr1 = (stage8_active) ? stage8_input0_address1 : 17'd0;
  assign mem_model_7_act_Mul_output_0_re1 = (stage8_active) ? stage8_input0_ce1 : 1'b0;
  assign mem_model_7_act_Mul_output_0_waddr0 = stage7_output0_address0;
  assign mem_model_7_act_Mul_output_0_we0 = stage7_active && stage7_output0_ce0 && stage7_output0_we0;
  assign mem_model_7_act_Mul_output_0_wdata0 = stage7_output0_d0;
  assign mem_model_7_act_Mul_output_0_waddr1 = stage7_output0_address1;
  assign mem_model_7_act_Mul_output_0_we1 = stage7_active && stage7_output0_ce1 && stage7_output0_we1;
  assign mem_model_7_act_Mul_output_0_wdata1 = stage7_output0_d1;
  yolo26n_sram_2r2w #(.ADDR_WIDTH(17), .DEPTH(102400)) u_mem_model_7_act_Mul_output_0 (
    .clock(clock),
    .raddr0(mem_model_7_act_Mul_output_0_raddr0),
    .raddr1(mem_model_7_act_Mul_output_0_raddr1),
    .re0(mem_model_7_act_Mul_output_0_re0),
    .re1(mem_model_7_act_Mul_output_0_re1),
    .rdata0(mem_model_7_act_Mul_output_0_rdata0),
    .rdata1(mem_model_7_act_Mul_output_0_rdata1),
    .waddr0(mem_model_7_act_Mul_output_0_waddr0),
    .waddr1(mem_model_7_act_Mul_output_0_waddr1),
    .we0(mem_model_7_act_Mul_output_0_we0),
    .we1(mem_model_7_act_Mul_output_0_we1),
    .wdata0(mem_model_7_act_Mul_output_0_wdata0),
    .wdata1(mem_model_7_act_Mul_output_0_wdata1)
  );

  wire [16:0] mem_model_8_cv2_act_Mul_output_0_raddr0;
  wire [16:0] mem_model_8_cv2_act_Mul_output_0_raddr1;
  wire mem_model_8_cv2_act_Mul_output_0_re0;
  wire mem_model_8_cv2_act_Mul_output_0_re1;
  wire [31:0] mem_model_8_cv2_act_Mul_output_0_rdata0;
  wire [31:0] mem_model_8_cv2_act_Mul_output_0_rdata1;
  wire [16:0] mem_model_8_cv2_act_Mul_output_0_waddr0;
  wire [16:0] mem_model_8_cv2_act_Mul_output_0_waddr1;
  wire mem_model_8_cv2_act_Mul_output_0_we0;
  wire mem_model_8_cv2_act_Mul_output_0_we1;
  wire [31:0] mem_model_8_cv2_act_Mul_output_0_wdata0;
  wire [31:0] mem_model_8_cv2_act_Mul_output_0_wdata1;
  assign mem_model_8_cv2_act_Mul_output_0_raddr0 = (stage9_active) ? stage9_input0_address0 : 17'd0;
  assign mem_model_8_cv2_act_Mul_output_0_re0 = (stage9_active) ? stage9_input0_ce0 : 1'b0;
  assign mem_model_8_cv2_act_Mul_output_0_raddr1 = (stage9_active) ? stage9_input0_address1 : 17'd0;
  assign mem_model_8_cv2_act_Mul_output_0_re1 = (stage9_active) ? stage9_input0_ce1 : 1'b0;
  assign mem_model_8_cv2_act_Mul_output_0_waddr0 = stage8_output0_address0;
  assign mem_model_8_cv2_act_Mul_output_0_we0 = stage8_active && stage8_output0_ce0 && stage8_output0_we0;
  assign mem_model_8_cv2_act_Mul_output_0_wdata0 = stage8_output0_d0;
  assign mem_model_8_cv2_act_Mul_output_0_waddr1 = stage8_output0_address1;
  assign mem_model_8_cv2_act_Mul_output_0_we1 = stage8_active && stage8_output0_ce1 && stage8_output0_we1;
  assign mem_model_8_cv2_act_Mul_output_0_wdata1 = stage8_output0_d1;
  yolo26n_sram_2r2w #(.ADDR_WIDTH(17), .DEPTH(102400)) u_mem_model_8_cv2_act_Mul_output_0 (
    .clock(clock),
    .raddr0(mem_model_8_cv2_act_Mul_output_0_raddr0),
    .raddr1(mem_model_8_cv2_act_Mul_output_0_raddr1),
    .re0(mem_model_8_cv2_act_Mul_output_0_re0),
    .re1(mem_model_8_cv2_act_Mul_output_0_re1),
    .rdata0(mem_model_8_cv2_act_Mul_output_0_rdata0),
    .rdata1(mem_model_8_cv2_act_Mul_output_0_rdata1),
    .waddr0(mem_model_8_cv2_act_Mul_output_0_waddr0),
    .waddr1(mem_model_8_cv2_act_Mul_output_0_waddr1),
    .we0(mem_model_8_cv2_act_Mul_output_0_we0),
    .we1(mem_model_8_cv2_act_Mul_output_0_we1),
    .wdata0(mem_model_8_cv2_act_Mul_output_0_wdata0),
    .wdata1(mem_model_8_cv2_act_Mul_output_0_wdata1)
  );

  wire [16:0] mem_model_9_Add_output_0_raddr0;
  wire [16:0] mem_model_9_Add_output_0_raddr1;
  wire mem_model_9_Add_output_0_re0;
  wire mem_model_9_Add_output_0_re1;
  wire [31:0] mem_model_9_Add_output_0_rdata0;
  wire [31:0] mem_model_9_Add_output_0_rdata1;
  wire [16:0] mem_model_9_Add_output_0_waddr0;
  wire [16:0] mem_model_9_Add_output_0_waddr1;
  wire mem_model_9_Add_output_0_we0;
  wire mem_model_9_Add_output_0_we1;
  wire [31:0] mem_model_9_Add_output_0_wdata0;
  wire [31:0] mem_model_9_Add_output_0_wdata1;
  assign mem_model_9_Add_output_0_raddr0 = (stage10_active) ? stage10_input0_address0 : 17'd0;
  assign mem_model_9_Add_output_0_re0 = (stage10_active) ? stage10_input0_ce0 : 1'b0;
  assign mem_model_9_Add_output_0_raddr1 = (stage10_active) ? stage10_input0_address1 : 17'd0;
  assign mem_model_9_Add_output_0_re1 = (stage10_active) ? stage10_input0_ce1 : 1'b0;
  assign mem_model_9_Add_output_0_waddr0 = stage9_output0_address0;
  assign mem_model_9_Add_output_0_we0 = stage9_active && stage9_output0_ce0 && stage9_output0_we0;
  assign mem_model_9_Add_output_0_wdata0 = stage9_output0_d0;
  assign mem_model_9_Add_output_0_waddr1 = stage9_output0_address1;
  assign mem_model_9_Add_output_0_we1 = stage9_active && stage9_output0_ce1 && stage9_output0_we1;
  assign mem_model_9_Add_output_0_wdata1 = stage9_output0_d1;
  yolo26n_sram_2r2w #(.ADDR_WIDTH(17), .DEPTH(102400)) u_mem_model_9_Add_output_0 (
    .clock(clock),
    .raddr0(mem_model_9_Add_output_0_raddr0),
    .raddr1(mem_model_9_Add_output_0_raddr1),
    .re0(mem_model_9_Add_output_0_re0),
    .re1(mem_model_9_Add_output_0_re1),
    .rdata0(mem_model_9_Add_output_0_rdata0),
    .rdata1(mem_model_9_Add_output_0_rdata1),
    .waddr0(mem_model_9_Add_output_0_waddr0),
    .waddr1(mem_model_9_Add_output_0_waddr1),
    .we0(mem_model_9_Add_output_0_we0),
    .we1(mem_model_9_Add_output_0_we1),
    .wdata0(mem_model_9_Add_output_0_wdata0),
    .wdata1(mem_model_9_Add_output_0_wdata1)
  );

  wire [16:0] mem_model_10_cv2_act_Mul_output_0_raddr0;
  wire [16:0] mem_model_10_cv2_act_Mul_output_0_raddr1;
  wire mem_model_10_cv2_act_Mul_output_0_re0;
  wire mem_model_10_cv2_act_Mul_output_0_re1;
  wire [31:0] mem_model_10_cv2_act_Mul_output_0_rdata0;
  wire [31:0] mem_model_10_cv2_act_Mul_output_0_rdata1;
  wire [16:0] mem_model_10_cv2_act_Mul_output_0_waddr0;
  wire [16:0] mem_model_10_cv2_act_Mul_output_0_waddr1;
  wire mem_model_10_cv2_act_Mul_output_0_we0;
  wire mem_model_10_cv2_act_Mul_output_0_we1;
  wire [31:0] mem_model_10_cv2_act_Mul_output_0_wdata0;
  wire [31:0] mem_model_10_cv2_act_Mul_output_0_wdata1;
  assign mem_model_10_cv2_act_Mul_output_0_raddr0 = (stage11_active) ? stage11_input0_address0 : (stage21_active) ? stage21_input1_address0 : 17'd0;
  assign mem_model_10_cv2_act_Mul_output_0_re0 = (stage11_active) ? stage11_input0_ce0 : (stage21_active) ? stage21_input1_ce0 : 1'b0;
  assign mem_model_10_cv2_act_Mul_output_0_raddr1 = (stage11_active) ? stage11_input0_address1 : (stage21_active) ? stage21_input1_address1 : 17'd0;
  assign mem_model_10_cv2_act_Mul_output_0_re1 = (stage11_active) ? stage11_input0_ce1 : (stage21_active) ? stage21_input1_ce1 : 1'b0;
  assign mem_model_10_cv2_act_Mul_output_0_waddr0 = stage10_output0_address0;
  assign mem_model_10_cv2_act_Mul_output_0_we0 = stage10_active && stage10_output0_ce0 && stage10_output0_we0;
  assign mem_model_10_cv2_act_Mul_output_0_wdata0 = stage10_output0_d0;
  assign mem_model_10_cv2_act_Mul_output_0_waddr1 = stage10_output0_address1;
  assign mem_model_10_cv2_act_Mul_output_0_we1 = stage10_active && stage10_output0_ce1 && stage10_output0_we1;
  assign mem_model_10_cv2_act_Mul_output_0_wdata1 = stage10_output0_d1;
  yolo26n_sram_2r2w #(.ADDR_WIDTH(17), .DEPTH(102400)) u_mem_model_10_cv2_act_Mul_output_0 (
    .clock(clock),
    .raddr0(mem_model_10_cv2_act_Mul_output_0_raddr0),
    .raddr1(mem_model_10_cv2_act_Mul_output_0_raddr1),
    .re0(mem_model_10_cv2_act_Mul_output_0_re0),
    .re1(mem_model_10_cv2_act_Mul_output_0_re1),
    .rdata0(mem_model_10_cv2_act_Mul_output_0_rdata0),
    .rdata1(mem_model_10_cv2_act_Mul_output_0_rdata1),
    .waddr0(mem_model_10_cv2_act_Mul_output_0_waddr0),
    .waddr1(mem_model_10_cv2_act_Mul_output_0_waddr1),
    .we0(mem_model_10_cv2_act_Mul_output_0_we0),
    .we1(mem_model_10_cv2_act_Mul_output_0_we1),
    .wdata0(mem_model_10_cv2_act_Mul_output_0_wdata0),
    .wdata1(mem_model_10_cv2_act_Mul_output_0_wdata1)
  );

  wire [18:0] mem_model_11_Resize_output_0_raddr0;
  wire [18:0] mem_model_11_Resize_output_0_raddr1;
  wire mem_model_11_Resize_output_0_re0;
  wire mem_model_11_Resize_output_0_re1;
  wire [31:0] mem_model_11_Resize_output_0_rdata0;
  wire [31:0] mem_model_11_Resize_output_0_rdata1;
  wire [18:0] mem_model_11_Resize_output_0_waddr0;
  wire [18:0] mem_model_11_Resize_output_0_waddr1;
  wire mem_model_11_Resize_output_0_we0;
  wire mem_model_11_Resize_output_0_we1;
  wire [31:0] mem_model_11_Resize_output_0_wdata0;
  wire [31:0] mem_model_11_Resize_output_0_wdata1;
  assign mem_model_11_Resize_output_0_raddr0 = (stage12_active) ? stage12_input0_address0 : 19'd0;
  assign mem_model_11_Resize_output_0_re0 = (stage12_active) ? stage12_input0_ce0 : 1'b0;
  assign mem_model_11_Resize_output_0_raddr1 = (stage12_active) ? stage12_input0_address1 : 19'd0;
  assign mem_model_11_Resize_output_0_re1 = (stage12_active) ? stage12_input0_ce1 : 1'b0;
  assign mem_model_11_Resize_output_0_waddr0 = stage11_output0_address0;
  assign mem_model_11_Resize_output_0_we0 = stage11_active && stage11_output0_ce0 && stage11_output0_we0;
  assign mem_model_11_Resize_output_0_wdata0 = stage11_output0_d0;
  assign mem_model_11_Resize_output_0_waddr1 = stage11_output0_address1;
  assign mem_model_11_Resize_output_0_we1 = stage11_active && stage11_output0_ce1 && stage11_output0_we1;
  assign mem_model_11_Resize_output_0_wdata1 = stage11_output0_d1;
  yolo26n_sram_2r2w #(.ADDR_WIDTH(19), .DEPTH(409600)) u_mem_model_11_Resize_output_0 (
    .clock(clock),
    .raddr0(mem_model_11_Resize_output_0_raddr0),
    .raddr1(mem_model_11_Resize_output_0_raddr1),
    .re0(mem_model_11_Resize_output_0_re0),
    .re1(mem_model_11_Resize_output_0_re1),
    .rdata0(mem_model_11_Resize_output_0_rdata0),
    .rdata1(mem_model_11_Resize_output_0_rdata1),
    .waddr0(mem_model_11_Resize_output_0_waddr0),
    .waddr1(mem_model_11_Resize_output_0_waddr1),
    .we0(mem_model_11_Resize_output_0_we0),
    .we1(mem_model_11_Resize_output_0_we1),
    .wdata0(mem_model_11_Resize_output_0_wdata0),
    .wdata1(mem_model_11_Resize_output_0_wdata1)
  );

  wire [19:0] mem_model_12_Concat_output_0_raddr0;
  wire [19:0] mem_model_12_Concat_output_0_raddr1;
  wire mem_model_12_Concat_output_0_re0;
  wire mem_model_12_Concat_output_0_re1;
  wire [31:0] mem_model_12_Concat_output_0_rdata0;
  wire [31:0] mem_model_12_Concat_output_0_rdata1;
  wire [19:0] mem_model_12_Concat_output_0_waddr0;
  wire [19:0] mem_model_12_Concat_output_0_waddr1;
  wire mem_model_12_Concat_output_0_we0;
  wire mem_model_12_Concat_output_0_we1;
  wire [31:0] mem_model_12_Concat_output_0_wdata0;
  wire [31:0] mem_model_12_Concat_output_0_wdata1;
  assign mem_model_12_Concat_output_0_raddr0 = (stage13_active) ? stage13_input0_address0 : 20'd0;
  assign mem_model_12_Concat_output_0_re0 = (stage13_active) ? stage13_input0_ce0 : 1'b0;
  assign mem_model_12_Concat_output_0_raddr1 = (stage13_active) ? stage13_input0_address1 : 20'd0;
  assign mem_model_12_Concat_output_0_re1 = (stage13_active) ? stage13_input0_ce1 : 1'b0;
  assign mem_model_12_Concat_output_0_waddr0 = stage12_output0_address0;
  assign mem_model_12_Concat_output_0_we0 = stage12_active && stage12_output0_ce0 && stage12_output0_we0;
  assign mem_model_12_Concat_output_0_wdata0 = stage12_output0_d0;
  assign mem_model_12_Concat_output_0_waddr1 = stage12_output0_address1;
  assign mem_model_12_Concat_output_0_we1 = stage12_active && stage12_output0_ce1 && stage12_output0_we1;
  assign mem_model_12_Concat_output_0_wdata1 = stage12_output0_d1;
  yolo26n_sram_2r2w #(.ADDR_WIDTH(20), .DEPTH(614400)) u_mem_model_12_Concat_output_0 (
    .clock(clock),
    .raddr0(mem_model_12_Concat_output_0_raddr0),
    .raddr1(mem_model_12_Concat_output_0_raddr1),
    .re0(mem_model_12_Concat_output_0_re0),
    .re1(mem_model_12_Concat_output_0_re1),
    .rdata0(mem_model_12_Concat_output_0_rdata0),
    .rdata1(mem_model_12_Concat_output_0_rdata1),
    .waddr0(mem_model_12_Concat_output_0_waddr0),
    .waddr1(mem_model_12_Concat_output_0_waddr1),
    .we0(mem_model_12_Concat_output_0_we0),
    .we1(mem_model_12_Concat_output_0_we1),
    .wdata0(mem_model_12_Concat_output_0_wdata0),
    .wdata1(mem_model_12_Concat_output_0_wdata1)
  );

  wire [17:0] mem_model_13_cv2_act_Mul_output_0_raddr0;
  wire [17:0] mem_model_13_cv2_act_Mul_output_0_raddr1;
  wire mem_model_13_cv2_act_Mul_output_0_re0;
  wire mem_model_13_cv2_act_Mul_output_0_re1;
  wire [31:0] mem_model_13_cv2_act_Mul_output_0_rdata0;
  wire [31:0] mem_model_13_cv2_act_Mul_output_0_rdata1;
  wire [17:0] mem_model_13_cv2_act_Mul_output_0_waddr0;
  wire [17:0] mem_model_13_cv2_act_Mul_output_0_waddr1;
  wire mem_model_13_cv2_act_Mul_output_0_we0;
  wire mem_model_13_cv2_act_Mul_output_0_we1;
  wire [31:0] mem_model_13_cv2_act_Mul_output_0_wdata0;
  wire [31:0] mem_model_13_cv2_act_Mul_output_0_wdata1;
  assign mem_model_13_cv2_act_Mul_output_0_raddr0 = (stage14_active) ? stage14_input0_address0 : (stage18_active) ? stage18_input1_address0 : 18'd0;
  assign mem_model_13_cv2_act_Mul_output_0_re0 = (stage14_active) ? stage14_input0_ce0 : (stage18_active) ? stage18_input1_ce0 : 1'b0;
  assign mem_model_13_cv2_act_Mul_output_0_raddr1 = (stage14_active) ? stage14_input0_address1 : (stage18_active) ? stage18_input1_address1 : 18'd0;
  assign mem_model_13_cv2_act_Mul_output_0_re1 = (stage14_active) ? stage14_input0_ce1 : (stage18_active) ? stage18_input1_ce1 : 1'b0;
  assign mem_model_13_cv2_act_Mul_output_0_waddr0 = stage13_output0_address0;
  assign mem_model_13_cv2_act_Mul_output_0_we0 = stage13_active && stage13_output0_ce0 && stage13_output0_we0;
  assign mem_model_13_cv2_act_Mul_output_0_wdata0 = stage13_output0_d0;
  assign mem_model_13_cv2_act_Mul_output_0_waddr1 = stage13_output0_address1;
  assign mem_model_13_cv2_act_Mul_output_0_we1 = stage13_active && stage13_output0_ce1 && stage13_output0_we1;
  assign mem_model_13_cv2_act_Mul_output_0_wdata1 = stage13_output0_d1;
  yolo26n_sram_2r2w #(.ADDR_WIDTH(18), .DEPTH(204800)) u_mem_model_13_cv2_act_Mul_output_0 (
    .clock(clock),
    .raddr0(mem_model_13_cv2_act_Mul_output_0_raddr0),
    .raddr1(mem_model_13_cv2_act_Mul_output_0_raddr1),
    .re0(mem_model_13_cv2_act_Mul_output_0_re0),
    .re1(mem_model_13_cv2_act_Mul_output_0_re1),
    .rdata0(mem_model_13_cv2_act_Mul_output_0_rdata0),
    .rdata1(mem_model_13_cv2_act_Mul_output_0_rdata1),
    .waddr0(mem_model_13_cv2_act_Mul_output_0_waddr0),
    .waddr1(mem_model_13_cv2_act_Mul_output_0_waddr1),
    .we0(mem_model_13_cv2_act_Mul_output_0_we0),
    .we1(mem_model_13_cv2_act_Mul_output_0_we1),
    .wdata0(mem_model_13_cv2_act_Mul_output_0_wdata0),
    .wdata1(mem_model_13_cv2_act_Mul_output_0_wdata1)
  );

  wire [19:0] mem_model_14_Resize_output_0_raddr0;
  wire [19:0] mem_model_14_Resize_output_0_raddr1;
  wire mem_model_14_Resize_output_0_re0;
  wire mem_model_14_Resize_output_0_re1;
  wire [31:0] mem_model_14_Resize_output_0_rdata0;
  wire [31:0] mem_model_14_Resize_output_0_rdata1;
  wire [19:0] mem_model_14_Resize_output_0_waddr0;
  wire [19:0] mem_model_14_Resize_output_0_waddr1;
  wire mem_model_14_Resize_output_0_we0;
  wire mem_model_14_Resize_output_0_we1;
  wire [31:0] mem_model_14_Resize_output_0_wdata0;
  wire [31:0] mem_model_14_Resize_output_0_wdata1;
  assign mem_model_14_Resize_output_0_raddr0 = (stage15_active) ? stage15_input0_address0 : 20'd0;
  assign mem_model_14_Resize_output_0_re0 = (stage15_active) ? stage15_input0_ce0 : 1'b0;
  assign mem_model_14_Resize_output_0_raddr1 = (stage15_active) ? stage15_input0_address1 : 20'd0;
  assign mem_model_14_Resize_output_0_re1 = (stage15_active) ? stage15_input0_ce1 : 1'b0;
  assign mem_model_14_Resize_output_0_waddr0 = stage14_output0_address0;
  assign mem_model_14_Resize_output_0_we0 = stage14_active && stage14_output0_ce0 && stage14_output0_we0;
  assign mem_model_14_Resize_output_0_wdata0 = stage14_output0_d0;
  assign mem_model_14_Resize_output_0_waddr1 = stage14_output0_address1;
  assign mem_model_14_Resize_output_0_we1 = stage14_active && stage14_output0_ce1 && stage14_output0_we1;
  assign mem_model_14_Resize_output_0_wdata1 = stage14_output0_d1;
  yolo26n_sram_2r2w #(.ADDR_WIDTH(20), .DEPTH(819200)) u_mem_model_14_Resize_output_0 (
    .clock(clock),
    .raddr0(mem_model_14_Resize_output_0_raddr0),
    .raddr1(mem_model_14_Resize_output_0_raddr1),
    .re0(mem_model_14_Resize_output_0_re0),
    .re1(mem_model_14_Resize_output_0_re1),
    .rdata0(mem_model_14_Resize_output_0_rdata0),
    .rdata1(mem_model_14_Resize_output_0_rdata1),
    .waddr0(mem_model_14_Resize_output_0_waddr0),
    .waddr1(mem_model_14_Resize_output_0_waddr1),
    .we0(mem_model_14_Resize_output_0_we0),
    .we1(mem_model_14_Resize_output_0_we1),
    .wdata0(mem_model_14_Resize_output_0_wdata0),
    .wdata1(mem_model_14_Resize_output_0_wdata1)
  );

  wire [20:0] mem_model_15_Concat_output_0_raddr0;
  wire [20:0] mem_model_15_Concat_output_0_raddr1;
  wire mem_model_15_Concat_output_0_re0;
  wire mem_model_15_Concat_output_0_re1;
  wire [31:0] mem_model_15_Concat_output_0_rdata0;
  wire [31:0] mem_model_15_Concat_output_0_rdata1;
  wire [20:0] mem_model_15_Concat_output_0_waddr0;
  wire [20:0] mem_model_15_Concat_output_0_waddr1;
  wire mem_model_15_Concat_output_0_we0;
  wire mem_model_15_Concat_output_0_we1;
  wire [31:0] mem_model_15_Concat_output_0_wdata0;
  wire [31:0] mem_model_15_Concat_output_0_wdata1;
  assign mem_model_15_Concat_output_0_raddr0 = (stage16_active) ? stage16_input0_address0 : 21'd0;
  assign mem_model_15_Concat_output_0_re0 = (stage16_active) ? stage16_input0_ce0 : 1'b0;
  assign mem_model_15_Concat_output_0_raddr1 = (stage16_active) ? stage16_input0_address1 : 21'd0;
  assign mem_model_15_Concat_output_0_re1 = (stage16_active) ? stage16_input0_ce1 : 1'b0;
  assign mem_model_15_Concat_output_0_waddr0 = stage15_output0_address0;
  assign mem_model_15_Concat_output_0_we0 = stage15_active && stage15_output0_ce0 && stage15_output0_we0;
  assign mem_model_15_Concat_output_0_wdata0 = stage15_output0_d0;
  assign mem_model_15_Concat_output_0_waddr1 = stage15_output0_address1;
  assign mem_model_15_Concat_output_0_we1 = stage15_active && stage15_output0_ce1 && stage15_output0_we1;
  assign mem_model_15_Concat_output_0_wdata1 = stage15_output0_d1;
  yolo26n_sram_2r2w #(.ADDR_WIDTH(21), .DEPTH(1638400)) u_mem_model_15_Concat_output_0 (
    .clock(clock),
    .raddr0(mem_model_15_Concat_output_0_raddr0),
    .raddr1(mem_model_15_Concat_output_0_raddr1),
    .re0(mem_model_15_Concat_output_0_re0),
    .re1(mem_model_15_Concat_output_0_re1),
    .rdata0(mem_model_15_Concat_output_0_rdata0),
    .rdata1(mem_model_15_Concat_output_0_rdata1),
    .waddr0(mem_model_15_Concat_output_0_waddr0),
    .waddr1(mem_model_15_Concat_output_0_waddr1),
    .we0(mem_model_15_Concat_output_0_we0),
    .we1(mem_model_15_Concat_output_0_we1),
    .wdata0(mem_model_15_Concat_output_0_wdata0),
    .wdata1(mem_model_15_Concat_output_0_wdata1)
  );

  wire [18:0] mem_model_16_cv2_act_Mul_output_0_raddr0;
  wire [18:0] mem_model_16_cv2_act_Mul_output_0_raddr1;
  wire mem_model_16_cv2_act_Mul_output_0_re0;
  wire mem_model_16_cv2_act_Mul_output_0_re1;
  wire [31:0] mem_model_16_cv2_act_Mul_output_0_rdata0;
  wire [31:0] mem_model_16_cv2_act_Mul_output_0_rdata1;
  wire [18:0] mem_model_16_cv2_act_Mul_output_0_waddr0;
  wire [18:0] mem_model_16_cv2_act_Mul_output_0_waddr1;
  wire mem_model_16_cv2_act_Mul_output_0_we0;
  wire mem_model_16_cv2_act_Mul_output_0_we1;
  wire [31:0] mem_model_16_cv2_act_Mul_output_0_wdata0;
  wire [31:0] mem_model_16_cv2_act_Mul_output_0_wdata1;
  assign mem_model_16_cv2_act_Mul_output_0_raddr0 = (stage17_active) ? stage17_input0_address0 : (stage23_active) ? stage23_input0_address0 : 19'd0;
  assign mem_model_16_cv2_act_Mul_output_0_re0 = (stage17_active) ? stage17_input0_ce0 : (stage23_active) ? stage23_input0_ce0 : 1'b0;
  assign mem_model_16_cv2_act_Mul_output_0_raddr1 = (stage17_active) ? stage17_input0_address1 : (stage23_active) ? stage23_input0_address1 : 19'd0;
  assign mem_model_16_cv2_act_Mul_output_0_re1 = (stage17_active) ? stage17_input0_ce1 : (stage23_active) ? stage23_input0_ce1 : 1'b0;
  assign mem_model_16_cv2_act_Mul_output_0_waddr0 = stage16_output0_address0;
  assign mem_model_16_cv2_act_Mul_output_0_we0 = stage16_active && stage16_output0_ce0 && stage16_output0_we0;
  assign mem_model_16_cv2_act_Mul_output_0_wdata0 = stage16_output0_d0;
  assign mem_model_16_cv2_act_Mul_output_0_waddr1 = stage16_output0_address1;
  assign mem_model_16_cv2_act_Mul_output_0_we1 = stage16_active && stage16_output0_ce1 && stage16_output0_we1;
  assign mem_model_16_cv2_act_Mul_output_0_wdata1 = stage16_output0_d1;
  yolo26n_sram_2r2w #(.ADDR_WIDTH(19), .DEPTH(409600)) u_mem_model_16_cv2_act_Mul_output_0 (
    .clock(clock),
    .raddr0(mem_model_16_cv2_act_Mul_output_0_raddr0),
    .raddr1(mem_model_16_cv2_act_Mul_output_0_raddr1),
    .re0(mem_model_16_cv2_act_Mul_output_0_re0),
    .re1(mem_model_16_cv2_act_Mul_output_0_re1),
    .rdata0(mem_model_16_cv2_act_Mul_output_0_rdata0),
    .rdata1(mem_model_16_cv2_act_Mul_output_0_rdata1),
    .waddr0(mem_model_16_cv2_act_Mul_output_0_waddr0),
    .waddr1(mem_model_16_cv2_act_Mul_output_0_waddr1),
    .we0(mem_model_16_cv2_act_Mul_output_0_we0),
    .we1(mem_model_16_cv2_act_Mul_output_0_we1),
    .wdata0(mem_model_16_cv2_act_Mul_output_0_wdata0),
    .wdata1(mem_model_16_cv2_act_Mul_output_0_wdata1)
  );

  wire [16:0] mem_model_17_act_Mul_output_0_raddr0;
  wire [16:0] mem_model_17_act_Mul_output_0_raddr1;
  wire mem_model_17_act_Mul_output_0_re0;
  wire mem_model_17_act_Mul_output_0_re1;
  wire [31:0] mem_model_17_act_Mul_output_0_rdata0;
  wire [31:0] mem_model_17_act_Mul_output_0_rdata1;
  wire [16:0] mem_model_17_act_Mul_output_0_waddr0;
  wire [16:0] mem_model_17_act_Mul_output_0_waddr1;
  wire mem_model_17_act_Mul_output_0_we0;
  wire mem_model_17_act_Mul_output_0_we1;
  wire [31:0] mem_model_17_act_Mul_output_0_wdata0;
  wire [31:0] mem_model_17_act_Mul_output_0_wdata1;
  assign mem_model_17_act_Mul_output_0_raddr0 = (stage18_active) ? stage18_input0_address0 : 17'd0;
  assign mem_model_17_act_Mul_output_0_re0 = (stage18_active) ? stage18_input0_ce0 : 1'b0;
  assign mem_model_17_act_Mul_output_0_raddr1 = (stage18_active) ? stage18_input0_address1 : 17'd0;
  assign mem_model_17_act_Mul_output_0_re1 = (stage18_active) ? stage18_input0_ce1 : 1'b0;
  assign mem_model_17_act_Mul_output_0_waddr0 = stage17_output0_address0;
  assign mem_model_17_act_Mul_output_0_we0 = stage17_active && stage17_output0_ce0 && stage17_output0_we0;
  assign mem_model_17_act_Mul_output_0_wdata0 = stage17_output0_d0;
  assign mem_model_17_act_Mul_output_0_waddr1 = stage17_output0_address1;
  assign mem_model_17_act_Mul_output_0_we1 = stage17_active && stage17_output0_ce1 && stage17_output0_we1;
  assign mem_model_17_act_Mul_output_0_wdata1 = stage17_output0_d1;
  yolo26n_sram_2r2w #(.ADDR_WIDTH(17), .DEPTH(102400)) u_mem_model_17_act_Mul_output_0 (
    .clock(clock),
    .raddr0(mem_model_17_act_Mul_output_0_raddr0),
    .raddr1(mem_model_17_act_Mul_output_0_raddr1),
    .re0(mem_model_17_act_Mul_output_0_re0),
    .re1(mem_model_17_act_Mul_output_0_re1),
    .rdata0(mem_model_17_act_Mul_output_0_rdata0),
    .rdata1(mem_model_17_act_Mul_output_0_rdata1),
    .waddr0(mem_model_17_act_Mul_output_0_waddr0),
    .waddr1(mem_model_17_act_Mul_output_0_waddr1),
    .we0(mem_model_17_act_Mul_output_0_we0),
    .we1(mem_model_17_act_Mul_output_0_we1),
    .wdata0(mem_model_17_act_Mul_output_0_wdata0),
    .wdata1(mem_model_17_act_Mul_output_0_wdata1)
  );

  wire [18:0] mem_model_18_Concat_output_0_raddr0;
  wire [18:0] mem_model_18_Concat_output_0_raddr1;
  wire mem_model_18_Concat_output_0_re0;
  wire mem_model_18_Concat_output_0_re1;
  wire [31:0] mem_model_18_Concat_output_0_rdata0;
  wire [31:0] mem_model_18_Concat_output_0_rdata1;
  wire [18:0] mem_model_18_Concat_output_0_waddr0;
  wire [18:0] mem_model_18_Concat_output_0_waddr1;
  wire mem_model_18_Concat_output_0_we0;
  wire mem_model_18_Concat_output_0_we1;
  wire [31:0] mem_model_18_Concat_output_0_wdata0;
  wire [31:0] mem_model_18_Concat_output_0_wdata1;
  assign mem_model_18_Concat_output_0_raddr0 = (stage19_active) ? stage19_input0_address0 : 19'd0;
  assign mem_model_18_Concat_output_0_re0 = (stage19_active) ? stage19_input0_ce0 : 1'b0;
  assign mem_model_18_Concat_output_0_raddr1 = (stage19_active) ? stage19_input0_address1 : 19'd0;
  assign mem_model_18_Concat_output_0_re1 = (stage19_active) ? stage19_input0_ce1 : 1'b0;
  assign mem_model_18_Concat_output_0_waddr0 = stage18_output0_address0;
  assign mem_model_18_Concat_output_0_we0 = stage18_active && stage18_output0_ce0 && stage18_output0_we0;
  assign mem_model_18_Concat_output_0_wdata0 = stage18_output0_d0;
  assign mem_model_18_Concat_output_0_waddr1 = stage18_output0_address1;
  assign mem_model_18_Concat_output_0_we1 = stage18_active && stage18_output0_ce1 && stage18_output0_we1;
  assign mem_model_18_Concat_output_0_wdata1 = stage18_output0_d1;
  yolo26n_sram_2r2w #(.ADDR_WIDTH(19), .DEPTH(307200)) u_mem_model_18_Concat_output_0 (
    .clock(clock),
    .raddr0(mem_model_18_Concat_output_0_raddr0),
    .raddr1(mem_model_18_Concat_output_0_raddr1),
    .re0(mem_model_18_Concat_output_0_re0),
    .re1(mem_model_18_Concat_output_0_re1),
    .rdata0(mem_model_18_Concat_output_0_rdata0),
    .rdata1(mem_model_18_Concat_output_0_rdata1),
    .waddr0(mem_model_18_Concat_output_0_waddr0),
    .waddr1(mem_model_18_Concat_output_0_waddr1),
    .we0(mem_model_18_Concat_output_0_we0),
    .we1(mem_model_18_Concat_output_0_we1),
    .wdata0(mem_model_18_Concat_output_0_wdata0),
    .wdata1(mem_model_18_Concat_output_0_wdata1)
  );

  wire [17:0] mem_model_19_cv2_act_Mul_output_0_raddr0;
  wire [17:0] mem_model_19_cv2_act_Mul_output_0_raddr1;
  wire mem_model_19_cv2_act_Mul_output_0_re0;
  wire mem_model_19_cv2_act_Mul_output_0_re1;
  wire [31:0] mem_model_19_cv2_act_Mul_output_0_rdata0;
  wire [31:0] mem_model_19_cv2_act_Mul_output_0_rdata1;
  wire [17:0] mem_model_19_cv2_act_Mul_output_0_waddr0;
  wire [17:0] mem_model_19_cv2_act_Mul_output_0_waddr1;
  wire mem_model_19_cv2_act_Mul_output_0_we0;
  wire mem_model_19_cv2_act_Mul_output_0_we1;
  wire [31:0] mem_model_19_cv2_act_Mul_output_0_wdata0;
  wire [31:0] mem_model_19_cv2_act_Mul_output_0_wdata1;
  assign mem_model_19_cv2_act_Mul_output_0_raddr0 = (stage20_active) ? stage20_input0_address0 : (stage23_active) ? stage23_input1_address0 : 18'd0;
  assign mem_model_19_cv2_act_Mul_output_0_re0 = (stage20_active) ? stage20_input0_ce0 : (stage23_active) ? stage23_input1_ce0 : 1'b0;
  assign mem_model_19_cv2_act_Mul_output_0_raddr1 = (stage20_active) ? stage20_input0_address1 : (stage23_active) ? stage23_input1_address1 : 18'd0;
  assign mem_model_19_cv2_act_Mul_output_0_re1 = (stage20_active) ? stage20_input0_ce1 : (stage23_active) ? stage23_input1_ce1 : 1'b0;
  assign mem_model_19_cv2_act_Mul_output_0_waddr0 = stage19_output0_address0;
  assign mem_model_19_cv2_act_Mul_output_0_we0 = stage19_active && stage19_output0_ce0 && stage19_output0_we0;
  assign mem_model_19_cv2_act_Mul_output_0_wdata0 = stage19_output0_d0;
  assign mem_model_19_cv2_act_Mul_output_0_waddr1 = stage19_output0_address1;
  assign mem_model_19_cv2_act_Mul_output_0_we1 = stage19_active && stage19_output0_ce1 && stage19_output0_we1;
  assign mem_model_19_cv2_act_Mul_output_0_wdata1 = stage19_output0_d1;
  yolo26n_sram_2r2w #(.ADDR_WIDTH(18), .DEPTH(204800)) u_mem_model_19_cv2_act_Mul_output_0 (
    .clock(clock),
    .raddr0(mem_model_19_cv2_act_Mul_output_0_raddr0),
    .raddr1(mem_model_19_cv2_act_Mul_output_0_raddr1),
    .re0(mem_model_19_cv2_act_Mul_output_0_re0),
    .re1(mem_model_19_cv2_act_Mul_output_0_re1),
    .rdata0(mem_model_19_cv2_act_Mul_output_0_rdata0),
    .rdata1(mem_model_19_cv2_act_Mul_output_0_rdata1),
    .waddr0(mem_model_19_cv2_act_Mul_output_0_waddr0),
    .waddr1(mem_model_19_cv2_act_Mul_output_0_waddr1),
    .we0(mem_model_19_cv2_act_Mul_output_0_we0),
    .we1(mem_model_19_cv2_act_Mul_output_0_we1),
    .wdata0(mem_model_19_cv2_act_Mul_output_0_wdata0),
    .wdata1(mem_model_19_cv2_act_Mul_output_0_wdata1)
  );

  wire [15:0] mem_model_20_act_Mul_output_0_raddr0;
  wire [15:0] mem_model_20_act_Mul_output_0_raddr1;
  wire mem_model_20_act_Mul_output_0_re0;
  wire mem_model_20_act_Mul_output_0_re1;
  wire [31:0] mem_model_20_act_Mul_output_0_rdata0;
  wire [31:0] mem_model_20_act_Mul_output_0_rdata1;
  wire [15:0] mem_model_20_act_Mul_output_0_waddr0;
  wire [15:0] mem_model_20_act_Mul_output_0_waddr1;
  wire mem_model_20_act_Mul_output_0_we0;
  wire mem_model_20_act_Mul_output_0_we1;
  wire [31:0] mem_model_20_act_Mul_output_0_wdata0;
  wire [31:0] mem_model_20_act_Mul_output_0_wdata1;
  assign mem_model_20_act_Mul_output_0_raddr0 = (stage21_active) ? stage21_input0_address0 : 16'd0;
  assign mem_model_20_act_Mul_output_0_re0 = (stage21_active) ? stage21_input0_ce0 : 1'b0;
  assign mem_model_20_act_Mul_output_0_raddr1 = (stage21_active) ? stage21_input0_address1 : 16'd0;
  assign mem_model_20_act_Mul_output_0_re1 = (stage21_active) ? stage21_input0_ce1 : 1'b0;
  assign mem_model_20_act_Mul_output_0_waddr0 = stage20_output0_address0;
  assign mem_model_20_act_Mul_output_0_we0 = stage20_active && stage20_output0_ce0 && stage20_output0_we0;
  assign mem_model_20_act_Mul_output_0_wdata0 = stage20_output0_d0;
  assign mem_model_20_act_Mul_output_0_waddr1 = stage20_output0_address1;
  assign mem_model_20_act_Mul_output_0_we1 = stage20_active && stage20_output0_ce1 && stage20_output0_we1;
  assign mem_model_20_act_Mul_output_0_wdata1 = stage20_output0_d1;
  yolo26n_sram_2r2w #(.ADDR_WIDTH(16), .DEPTH(51200)) u_mem_model_20_act_Mul_output_0 (
    .clock(clock),
    .raddr0(mem_model_20_act_Mul_output_0_raddr0),
    .raddr1(mem_model_20_act_Mul_output_0_raddr1),
    .re0(mem_model_20_act_Mul_output_0_re0),
    .re1(mem_model_20_act_Mul_output_0_re1),
    .rdata0(mem_model_20_act_Mul_output_0_rdata0),
    .rdata1(mem_model_20_act_Mul_output_0_rdata1),
    .waddr0(mem_model_20_act_Mul_output_0_waddr0),
    .waddr1(mem_model_20_act_Mul_output_0_waddr1),
    .we0(mem_model_20_act_Mul_output_0_we0),
    .we1(mem_model_20_act_Mul_output_0_we1),
    .wdata0(mem_model_20_act_Mul_output_0_wdata0),
    .wdata1(mem_model_20_act_Mul_output_0_wdata1)
  );

  wire [17:0] mem_model_21_Concat_output_0_raddr0;
  wire [17:0] mem_model_21_Concat_output_0_raddr1;
  wire mem_model_21_Concat_output_0_re0;
  wire mem_model_21_Concat_output_0_re1;
  wire [31:0] mem_model_21_Concat_output_0_rdata0;
  wire [31:0] mem_model_21_Concat_output_0_rdata1;
  wire [17:0] mem_model_21_Concat_output_0_waddr0;
  wire [17:0] mem_model_21_Concat_output_0_waddr1;
  wire mem_model_21_Concat_output_0_we0;
  wire mem_model_21_Concat_output_0_we1;
  wire [31:0] mem_model_21_Concat_output_0_wdata0;
  wire [31:0] mem_model_21_Concat_output_0_wdata1;
  assign mem_model_21_Concat_output_0_raddr0 = (stage22_active) ? stage22_input0_address0 : 18'd0;
  assign mem_model_21_Concat_output_0_re0 = (stage22_active) ? stage22_input0_ce0 : 1'b0;
  assign mem_model_21_Concat_output_0_raddr1 = (stage22_active) ? stage22_input0_address1 : 18'd0;
  assign mem_model_21_Concat_output_0_re1 = (stage22_active) ? stage22_input0_ce1 : 1'b0;
  assign mem_model_21_Concat_output_0_waddr0 = stage21_output0_address0;
  assign mem_model_21_Concat_output_0_we0 = stage21_active && stage21_output0_ce0 && stage21_output0_we0;
  assign mem_model_21_Concat_output_0_wdata0 = stage21_output0_d0;
  assign mem_model_21_Concat_output_0_waddr1 = stage21_output0_address1;
  assign mem_model_21_Concat_output_0_we1 = stage21_active && stage21_output0_ce1 && stage21_output0_we1;
  assign mem_model_21_Concat_output_0_wdata1 = stage21_output0_d1;
  yolo26n_sram_2r2w #(.ADDR_WIDTH(18), .DEPTH(153600)) u_mem_model_21_Concat_output_0 (
    .clock(clock),
    .raddr0(mem_model_21_Concat_output_0_raddr0),
    .raddr1(mem_model_21_Concat_output_0_raddr1),
    .re0(mem_model_21_Concat_output_0_re0),
    .re1(mem_model_21_Concat_output_0_re1),
    .rdata0(mem_model_21_Concat_output_0_rdata0),
    .rdata1(mem_model_21_Concat_output_0_rdata1),
    .waddr0(mem_model_21_Concat_output_0_waddr0),
    .waddr1(mem_model_21_Concat_output_0_waddr1),
    .we0(mem_model_21_Concat_output_0_we0),
    .we1(mem_model_21_Concat_output_0_we1),
    .wdata0(mem_model_21_Concat_output_0_wdata0),
    .wdata1(mem_model_21_Concat_output_0_wdata1)
  );

  wire [16:0] mem_model_22_cv2_act_Mul_output_0_raddr0;
  wire [16:0] mem_model_22_cv2_act_Mul_output_0_raddr1;
  wire mem_model_22_cv2_act_Mul_output_0_re0;
  wire mem_model_22_cv2_act_Mul_output_0_re1;
  wire [31:0] mem_model_22_cv2_act_Mul_output_0_rdata0;
  wire [31:0] mem_model_22_cv2_act_Mul_output_0_rdata1;
  wire [16:0] mem_model_22_cv2_act_Mul_output_0_waddr0;
  wire [16:0] mem_model_22_cv2_act_Mul_output_0_waddr1;
  wire mem_model_22_cv2_act_Mul_output_0_we0;
  wire mem_model_22_cv2_act_Mul_output_0_we1;
  wire [31:0] mem_model_22_cv2_act_Mul_output_0_wdata0;
  wire [31:0] mem_model_22_cv2_act_Mul_output_0_wdata1;
  assign mem_model_22_cv2_act_Mul_output_0_raddr0 = (stage23_active) ? stage23_input2_address0 : 17'd0;
  assign mem_model_22_cv2_act_Mul_output_0_re0 = (stage23_active) ? stage23_input2_ce0 : 1'b0;
  assign mem_model_22_cv2_act_Mul_output_0_raddr1 = (stage23_active) ? stage23_input2_address1 : 17'd0;
  assign mem_model_22_cv2_act_Mul_output_0_re1 = (stage23_active) ? stage23_input2_ce1 : 1'b0;
  assign mem_model_22_cv2_act_Mul_output_0_waddr0 = stage22_output0_address0;
  assign mem_model_22_cv2_act_Mul_output_0_we0 = stage22_active && stage22_output0_ce0 && stage22_output0_we0;
  assign mem_model_22_cv2_act_Mul_output_0_wdata0 = stage22_output0_d0;
  assign mem_model_22_cv2_act_Mul_output_0_waddr1 = stage22_output0_address1;
  assign mem_model_22_cv2_act_Mul_output_0_we1 = stage22_active && stage22_output0_ce1 && stage22_output0_we1;
  assign mem_model_22_cv2_act_Mul_output_0_wdata1 = stage22_output0_d1;
  yolo26n_sram_2r2w #(.ADDR_WIDTH(17), .DEPTH(102400)) u_mem_model_22_cv2_act_Mul_output_0 (
    .clock(clock),
    .raddr0(mem_model_22_cv2_act_Mul_output_0_raddr0),
    .raddr1(mem_model_22_cv2_act_Mul_output_0_raddr1),
    .re0(mem_model_22_cv2_act_Mul_output_0_re0),
    .re1(mem_model_22_cv2_act_Mul_output_0_re1),
    .rdata0(mem_model_22_cv2_act_Mul_output_0_rdata0),
    .rdata1(mem_model_22_cv2_act_Mul_output_0_rdata1),
    .waddr0(mem_model_22_cv2_act_Mul_output_0_waddr0),
    .waddr1(mem_model_22_cv2_act_Mul_output_0_waddr1),
    .we0(mem_model_22_cv2_act_Mul_output_0_we0),
    .we1(mem_model_22_cv2_act_Mul_output_0_we1),
    .wdata0(mem_model_22_cv2_act_Mul_output_0_wdata0),
    .wdata1(mem_model_22_cv2_act_Mul_output_0_wdata1)
  );

  wire [10:0] mem_output0_raddr0;
  wire [10:0] mem_output0_raddr1;
  wire mem_output0_re0;
  wire mem_output0_re1;
  wire [31:0] mem_output0_rdata0;
  wire [31:0] mem_output0_rdata1;
  wire [10:0] mem_output0_waddr0;
  wire [10:0] mem_output0_waddr1;
  wire mem_output0_we0;
  wire mem_output0_we1;
  wire [31:0] mem_output0_wdata0;
  wire [31:0] mem_output0_wdata1;
  assign mem_output0_raddr0 = host_output_addr;
  assign mem_output0_re0 = 1'b1;
  assign mem_output0_raddr1 = 11'd0;
  assign mem_output0_re1 = 1'b0;
  assign mem_output0_waddr0 = stage23_output0_address0;
  assign mem_output0_we0 = stage23_active && stage23_output0_ce0 && stage23_output0_we0;
  assign mem_output0_wdata0 = stage23_output0_d0;
  assign mem_output0_waddr1 = stage23_output0_address1;
  assign mem_output0_we1 = stage23_active && stage23_output0_ce1 && stage23_output0_we1;
  assign mem_output0_wdata1 = stage23_output0_d1;
  yolo26n_sram_2r2w #(.ADDR_WIDTH(11), .DEPTH(1800)) u_mem_output0 (
    .clock(clock),
    .raddr0(mem_output0_raddr0),
    .raddr1(mem_output0_raddr1),
    .re0(mem_output0_re0),
    .re1(mem_output0_re1),
    .rdata0(mem_output0_rdata0),
    .rdata1(mem_output0_rdata1),
    .waddr0(mem_output0_waddr0),
    .waddr1(mem_output0_waddr1),
    .we0(mem_output0_we0),
    .we1(mem_output0_we1),
    .wdata0(mem_output0_wdata0),
    .wdata1(mem_output0_wdata1)
  );

  assign stage0_input_q0 = mem_images_rdata0;
  assign stage0_input_q1 = mem_images_rdata1;

  assign stage1_input_q0 = mem_model_0_act_Mul_output_0_rdata0;
  assign stage1_input_q1 = mem_model_0_act_Mul_output_0_rdata1;

  assign stage2_input0_q0 = mem_model_1_act_Mul_output_0_rdata0;
  assign stage2_input0_q1 = mem_model_1_act_Mul_output_0_rdata1;

  assign stage3_input0_q0 = mem_model_2_cv2_act_Mul_output_0_rdata0;
  assign stage3_input0_q1 = mem_model_2_cv2_act_Mul_output_0_rdata1;

  assign stage4_input0_q0 = mem_model_3_act_Mul_output_0_rdata0;
  assign stage4_input0_q1 = mem_model_3_act_Mul_output_0_rdata1;

  assign stage5_input0_q0 = mem_model_4_cv2_act_Mul_output_0_rdata0;
  assign stage5_input0_q1 = mem_model_4_cv2_act_Mul_output_0_rdata1;

  assign stage6_input0_q0 = mem_model_5_act_Mul_output_0_rdata0;
  assign stage6_input0_q1 = mem_model_5_act_Mul_output_0_rdata1;

  assign stage7_input0_q0 = mem_model_6_cv2_act_Mul_output_0_rdata0;
  assign stage7_input0_q1 = mem_model_6_cv2_act_Mul_output_0_rdata1;

  assign stage8_input0_q0 = mem_model_7_act_Mul_output_0_rdata0;
  assign stage8_input0_q1 = mem_model_7_act_Mul_output_0_rdata1;

  assign stage9_input0_q0 = mem_model_8_cv2_act_Mul_output_0_rdata0;
  assign stage9_input0_q1 = mem_model_8_cv2_act_Mul_output_0_rdata1;

  assign stage10_input0_q0 = mem_model_9_Add_output_0_rdata0;
  assign stage10_input0_q1 = mem_model_9_Add_output_0_rdata1;

  assign stage11_input0_q0 = mem_model_10_cv2_act_Mul_output_0_rdata0;
  assign stage11_input0_q1 = mem_model_10_cv2_act_Mul_output_0_rdata1;

  assign stage12_input0_q0 = mem_model_11_Resize_output_0_rdata0;
  assign stage12_input0_q1 = mem_model_11_Resize_output_0_rdata1;
  assign stage12_input1_q0 = mem_model_6_cv2_act_Mul_output_0_rdata0;
  assign stage12_input1_q1 = mem_model_6_cv2_act_Mul_output_0_rdata1;

  assign stage13_input0_q0 = mem_model_12_Concat_output_0_rdata0;
  assign stage13_input0_q1 = mem_model_12_Concat_output_0_rdata1;

  assign stage14_input0_q0 = mem_model_13_cv2_act_Mul_output_0_rdata0;
  assign stage14_input0_q1 = mem_model_13_cv2_act_Mul_output_0_rdata1;

  assign stage15_input0_q0 = mem_model_14_Resize_output_0_rdata0;
  assign stage15_input0_q1 = mem_model_14_Resize_output_0_rdata1;
  assign stage15_input1_q0 = mem_model_4_cv2_act_Mul_output_0_rdata0;
  assign stage15_input1_q1 = mem_model_4_cv2_act_Mul_output_0_rdata1;

  assign stage16_input0_q0 = mem_model_15_Concat_output_0_rdata0;
  assign stage16_input0_q1 = mem_model_15_Concat_output_0_rdata1;

  assign stage17_input0_q0 = mem_model_16_cv2_act_Mul_output_0_rdata0;
  assign stage17_input0_q1 = mem_model_16_cv2_act_Mul_output_0_rdata1;

  assign stage18_input0_q0 = mem_model_17_act_Mul_output_0_rdata0;
  assign stage18_input0_q1 = mem_model_17_act_Mul_output_0_rdata1;
  assign stage18_input1_q0 = mem_model_13_cv2_act_Mul_output_0_rdata0;
  assign stage18_input1_q1 = mem_model_13_cv2_act_Mul_output_0_rdata1;

  assign stage19_input0_q0 = mem_model_18_Concat_output_0_rdata0;
  assign stage19_input0_q1 = mem_model_18_Concat_output_0_rdata1;

  assign stage20_input0_q0 = mem_model_19_cv2_act_Mul_output_0_rdata0;
  assign stage20_input0_q1 = mem_model_19_cv2_act_Mul_output_0_rdata1;

  assign stage21_input0_q0 = mem_model_20_act_Mul_output_0_rdata0;
  assign stage21_input0_q1 = mem_model_20_act_Mul_output_0_rdata1;
  assign stage21_input1_q0 = mem_model_10_cv2_act_Mul_output_0_rdata0;
  assign stage21_input1_q1 = mem_model_10_cv2_act_Mul_output_0_rdata1;

  assign stage22_input0_q0 = mem_model_21_Concat_output_0_rdata0;
  assign stage22_input0_q1 = mem_model_21_Concat_output_0_rdata1;

  assign stage23_input0_q0 = mem_model_16_cv2_act_Mul_output_0_rdata0;
  assign stage23_input0_q1 = mem_model_16_cv2_act_Mul_output_0_rdata1;
  assign stage23_input1_q0 = mem_model_19_cv2_act_Mul_output_0_rdata0;
  assign stage23_input1_q1 = mem_model_19_cv2_act_Mul_output_0_rdata1;
  assign stage23_input2_q0 = mem_model_22_cv2_act_Mul_output_0_rdata0;
  assign stage23_input2_q1 = mem_model_22_cv2_act_Mul_output_0_rdata1;

  assign host_output_data = mem_output0_rdata0;

  always @(posedge clock) begin
    if (reset) begin
      running <= 1'b0;
      active_stage <= 5'd0;
      stage_start <= {STAGE_COUNT{1'b0}};
      done <= 1'b0;
    end else begin
      stage_start <= {STAGE_COUNT{1'b0}};
      done <= 1'b0;
      if (!running) begin
        active_stage <= 5'd0;
        if (start) begin
          running <= 1'b1;
          active_stage <= 5'd0;
          stage_start[0] <= 1'b1;
        end
      end else begin
        case (active_stage)
          5'd0: begin
            if (stage0_done) begin
              active_stage <= 5'd1;
              stage_start[1] <= 1'b1;
            end
          end
          5'd1: begin
            if (stage1_done) begin
              active_stage <= 5'd2;
              stage_start[2] <= 1'b1;
            end
          end
          5'd2: begin
            if (stage2_done) begin
              active_stage <= 5'd3;
              stage_start[3] <= 1'b1;
            end
          end
          5'd3: begin
            if (stage3_done) begin
              active_stage <= 5'd4;
              stage_start[4] <= 1'b1;
            end
          end
          5'd4: begin
            if (stage4_done) begin
              active_stage <= 5'd5;
              stage_start[5] <= 1'b1;
            end
          end
          5'd5: begin
            if (stage5_done) begin
              active_stage <= 5'd6;
              stage_start[6] <= 1'b1;
            end
          end
          5'd6: begin
            if (stage6_done) begin
              active_stage <= 5'd7;
              stage_start[7] <= 1'b1;
            end
          end
          5'd7: begin
            if (stage7_done) begin
              active_stage <= 5'd8;
              stage_start[8] <= 1'b1;
            end
          end
          5'd8: begin
            if (stage8_done) begin
              active_stage <= 5'd9;
              stage_start[9] <= 1'b1;
            end
          end
          5'd9: begin
            if (stage9_done) begin
              active_stage <= 5'd10;
              stage_start[10] <= 1'b1;
            end
          end
          5'd10: begin
            if (stage10_done) begin
              active_stage <= 5'd11;
              stage_start[11] <= 1'b1;
            end
          end
          5'd11: begin
            if (stage11_done) begin
              active_stage <= 5'd12;
              stage_start[12] <= 1'b1;
            end
          end
          5'd12: begin
            if (stage12_done) begin
              active_stage <= 5'd13;
              stage_start[13] <= 1'b1;
            end
          end
          5'd13: begin
            if (stage13_done) begin
              active_stage <= 5'd14;
              stage_start[14] <= 1'b1;
            end
          end
          5'd14: begin
            if (stage14_done) begin
              active_stage <= 5'd15;
              stage_start[15] <= 1'b1;
            end
          end
          5'd15: begin
            if (stage15_done) begin
              active_stage <= 5'd16;
              stage_start[16] <= 1'b1;
            end
          end
          5'd16: begin
            if (stage16_done) begin
              active_stage <= 5'd17;
              stage_start[17] <= 1'b1;
            end
          end
          5'd17: begin
            if (stage17_done) begin
              active_stage <= 5'd18;
              stage_start[18] <= 1'b1;
            end
          end
          5'd18: begin
            if (stage18_done) begin
              active_stage <= 5'd19;
              stage_start[19] <= 1'b1;
            end
          end
          5'd19: begin
            if (stage19_done) begin
              active_stage <= 5'd20;
              stage_start[20] <= 1'b1;
            end
          end
          5'd20: begin
            if (stage20_done) begin
              active_stage <= 5'd21;
              stage_start[21] <= 1'b1;
            end
          end
          5'd21: begin
            if (stage21_done) begin
              active_stage <= 5'd22;
              stage_start[22] <= 1'b1;
            end
          end
          5'd22: begin
            if (stage22_done) begin
              active_stage <= 5'd23;
              stage_start[23] <= 1'b1;
            end
          end
          5'd23: begin
            if (stage23_done) begin
              running <= 1'b0;
              done <= 1'b1;
            end
          end
          default: begin
            running <= 1'b0;
            done <= 1'b0;
          end
        endcase
      end
    end
  end

  _Z14yolo26n_stage0PKfPf u_stage0 (
    .clock(clock),
    .reset(reset),
    .start_port(stage_start[0]),
    .input_q0(stage0_input_q0),
    .input_q1(stage0_input_q1),
    .done_port(stage0_done),
    .input_address0(stage0_input_address0),
    .input_address1(stage0_input_address1),
    .input_ce0(stage0_input_ce0),
    .input_ce1(stage0_input_ce1),
    .output_address0(stage0_output_address0),
    .output_address1(stage0_output_address1),
    .output_ce0(stage0_output_ce0),
    .output_ce1(stage0_output_ce1),
    .output_we0(stage0_output_we0),
    .output_we1(stage0_output_we1),
    .output_d0(stage0_output_d0),
    .output_d1(stage0_output_d1)
  );

  _Z14yolo26n_stage1PKfPf u_stage1 (
    .clock(clock),
    .reset(reset),
    .start_port(stage_start[1]),
    .input_q0(stage1_input_q0),
    .input_q1(stage1_input_q1),
    .done_port(stage1_done),
    .input_address0(stage1_input_address0),
    .input_address1(stage1_input_address1),
    .input_ce0(stage1_input_ce0),
    .input_ce1(stage1_input_ce1),
    .output_address0(stage1_output_address0),
    .output_address1(stage1_output_address1),
    .output_ce0(stage1_output_ce0),
    .output_ce1(stage1_output_ce1),
    .output_we0(stage1_output_we0),
    .output_we1(stage1_output_we1),
    .output_d0(stage1_output_d0),
    .output_d1(stage1_output_d1)
  );

  _Z14yolo26n_stage2PKfPf u_stage2 (
    .clock(clock),
    .reset(reset),
    .start_port(stage_start[2]),
    .input0_q0(stage2_input0_q0),
    .input0_q1(stage2_input0_q1),
    .done_port(stage2_done),
    .input0_address0(stage2_input0_address0),
    .input0_address1(stage2_input0_address1),
    .input0_ce0(stage2_input0_ce0),
    .input0_ce1(stage2_input0_ce1),
    .output0_address0(stage2_output0_address0),
    .output0_address1(stage2_output0_address1),
    .output0_ce0(stage2_output0_ce0),
    .output0_ce1(stage2_output0_ce1),
    .output0_we0(stage2_output0_we0),
    .output0_we1(stage2_output0_we1),
    .output0_d0(stage2_output0_d0),
    .output0_d1(stage2_output0_d1)
  );

  _Z14yolo26n_stage3PKfPf u_stage3 (
    .clock(clock),
    .reset(reset),
    .start_port(stage_start[3]),
    .input0_q0(stage3_input0_q0),
    .input0_q1(stage3_input0_q1),
    .done_port(stage3_done),
    .input0_address0(stage3_input0_address0),
    .input0_address1(stage3_input0_address1),
    .input0_ce0(stage3_input0_ce0),
    .input0_ce1(stage3_input0_ce1),
    .output0_address0(stage3_output0_address0),
    .output0_address1(stage3_output0_address1),
    .output0_ce0(stage3_output0_ce0),
    .output0_ce1(stage3_output0_ce1),
    .output0_we0(stage3_output0_we0),
    .output0_we1(stage3_output0_we1),
    .output0_d0(stage3_output0_d0),
    .output0_d1(stage3_output0_d1)
  );

  _Z14yolo26n_stage4PKfPf u_stage4 (
    .clock(clock),
    .reset(reset),
    .start_port(stage_start[4]),
    .input0_q0(stage4_input0_q0),
    .input0_q1(stage4_input0_q1),
    .done_port(stage4_done),
    .input0_address0(stage4_input0_address0),
    .input0_address1(stage4_input0_address1),
    .input0_ce0(stage4_input0_ce0),
    .input0_ce1(stage4_input0_ce1),
    .output0_address0(stage4_output0_address0),
    .output0_address1(stage4_output0_address1),
    .output0_ce0(stage4_output0_ce0),
    .output0_ce1(stage4_output0_ce1),
    .output0_we0(stage4_output0_we0),
    .output0_we1(stage4_output0_we1),
    .output0_d0(stage4_output0_d0),
    .output0_d1(stage4_output0_d1)
  );

  _Z14yolo26n_stage5PKfPf u_stage5 (
    .clock(clock),
    .reset(reset),
    .start_port(stage_start[5]),
    .input0_q0(stage5_input0_q0),
    .input0_q1(stage5_input0_q1),
    .done_port(stage5_done),
    .input0_address0(stage5_input0_address0),
    .input0_address1(stage5_input0_address1),
    .input0_ce0(stage5_input0_ce0),
    .input0_ce1(stage5_input0_ce1),
    .output0_address0(stage5_output0_address0),
    .output0_address1(stage5_output0_address1),
    .output0_ce0(stage5_output0_ce0),
    .output0_ce1(stage5_output0_ce1),
    .output0_we0(stage5_output0_we0),
    .output0_we1(stage5_output0_we1),
    .output0_d0(stage5_output0_d0),
    .output0_d1(stage5_output0_d1)
  );

  _Z14yolo26n_stage6PKfPf u_stage6 (
    .clock(clock),
    .reset(reset),
    .start_port(stage_start[6]),
    .input0_q0(stage6_input0_q0),
    .input0_q1(stage6_input0_q1),
    .done_port(stage6_done),
    .input0_address0(stage6_input0_address0),
    .input0_address1(stage6_input0_address1),
    .input0_ce0(stage6_input0_ce0),
    .input0_ce1(stage6_input0_ce1),
    .output0_address0(stage6_output0_address0),
    .output0_address1(stage6_output0_address1),
    .output0_ce0(stage6_output0_ce0),
    .output0_ce1(stage6_output0_ce1),
    .output0_we0(stage6_output0_we0),
    .output0_we1(stage6_output0_we1),
    .output0_d0(stage6_output0_d0),
    .output0_d1(stage6_output0_d1)
  );

  _Z14yolo26n_stage7PKfPf u_stage7 (
    .clock(clock),
    .reset(reset),
    .start_port(stage_start[7]),
    .input0_q0(stage7_input0_q0),
    .input0_q1(stage7_input0_q1),
    .done_port(stage7_done),
    .input0_address0(stage7_input0_address0),
    .input0_address1(stage7_input0_address1),
    .input0_ce0(stage7_input0_ce0),
    .input0_ce1(stage7_input0_ce1),
    .output0_address0(stage7_output0_address0),
    .output0_address1(stage7_output0_address1),
    .output0_ce0(stage7_output0_ce0),
    .output0_ce1(stage7_output0_ce1),
    .output0_we0(stage7_output0_we0),
    .output0_we1(stage7_output0_we1),
    .output0_d0(stage7_output0_d0),
    .output0_d1(stage7_output0_d1)
  );

  _Z14yolo26n_stage8PKfPf u_stage8 (
    .clock(clock),
    .reset(reset),
    .start_port(stage_start[8]),
    .input0_q0(stage8_input0_q0),
    .input0_q1(stage8_input0_q1),
    .done_port(stage8_done),
    .input0_address0(stage8_input0_address0),
    .input0_address1(stage8_input0_address1),
    .input0_ce0(stage8_input0_ce0),
    .input0_ce1(stage8_input0_ce1),
    .output0_address0(stage8_output0_address0),
    .output0_address1(stage8_output0_address1),
    .output0_ce0(stage8_output0_ce0),
    .output0_ce1(stage8_output0_ce1),
    .output0_we0(stage8_output0_we0),
    .output0_we1(stage8_output0_we1),
    .output0_d0(stage8_output0_d0),
    .output0_d1(stage8_output0_d1)
  );

  _Z14yolo26n_stage9PKfPf u_stage9 (
    .clock(clock),
    .reset(reset),
    .start_port(stage_start[9]),
    .input0_q0(stage9_input0_q0),
    .input0_q1(stage9_input0_q1),
    .done_port(stage9_done),
    .input0_address0(stage9_input0_address0),
    .input0_address1(stage9_input0_address1),
    .input0_ce0(stage9_input0_ce0),
    .input0_ce1(stage9_input0_ce1),
    .output0_address0(stage9_output0_address0),
    .output0_address1(stage9_output0_address1),
    .output0_ce0(stage9_output0_ce0),
    .output0_ce1(stage9_output0_ce1),
    .output0_we0(stage9_output0_we0),
    .output0_we1(stage9_output0_we1),
    .output0_d0(stage9_output0_d0),
    .output0_d1(stage9_output0_d1)
  );

  _Z15yolo26n_stage10PKfPf u_stage10 (
    .clock(clock),
    .reset(reset),
    .start_port(stage_start[10]),
    .input0_q0(stage10_input0_q0),
    .input0_q1(stage10_input0_q1),
    .done_port(stage10_done),
    .input0_address0(stage10_input0_address0),
    .input0_address1(stage10_input0_address1),
    .input0_ce0(stage10_input0_ce0),
    .input0_ce1(stage10_input0_ce1),
    .output0_address0(stage10_output0_address0),
    .output0_address1(stage10_output0_address1),
    .output0_ce0(stage10_output0_ce0),
    .output0_ce1(stage10_output0_ce1),
    .output0_we0(stage10_output0_we0),
    .output0_we1(stage10_output0_we1),
    .output0_d0(stage10_output0_d0),
    .output0_d1(stage10_output0_d1)
  );

  _Z15yolo26n_stage11PKfPf u_stage11 (
    .clock(clock),
    .reset(reset),
    .start_port(stage_start[11]),
    .input0_q0(stage11_input0_q0),
    .input0_q1(stage11_input0_q1),
    .done_port(stage11_done),
    .input0_address0(stage11_input0_address0),
    .input0_address1(stage11_input0_address1),
    .input0_ce0(stage11_input0_ce0),
    .input0_ce1(stage11_input0_ce1),
    .output0_address0(stage11_output0_address0),
    .output0_address1(stage11_output0_address1),
    .output0_ce0(stage11_output0_ce0),
    .output0_ce1(stage11_output0_ce1),
    .output0_we0(stage11_output0_we0),
    .output0_we1(stage11_output0_we1),
    .output0_d0(stage11_output0_d0),
    .output0_d1(stage11_output0_d1)
  );

  _Z15yolo26n_stage12PKfS0_Pf u_stage12 (
    .clock(clock),
    .reset(reset),
    .start_port(stage_start[12]),
    .input0_q0(stage12_input0_q0),
    .input0_q1(stage12_input0_q1),
    .input1_q0(stage12_input1_q0),
    .input1_q1(stage12_input1_q1),
    .done_port(stage12_done),
    .input0_address0(stage12_input0_address0),
    .input0_address1(stage12_input0_address1),
    .input0_ce0(stage12_input0_ce0),
    .input0_ce1(stage12_input0_ce1),
    .input1_address0(stage12_input1_address0),
    .input1_address1(stage12_input1_address1),
    .input1_ce0(stage12_input1_ce0),
    .input1_ce1(stage12_input1_ce1),
    .output0_address0(stage12_output0_address0),
    .output0_address1(stage12_output0_address1),
    .output0_ce0(stage12_output0_ce0),
    .output0_ce1(stage12_output0_ce1),
    .output0_we0(stage12_output0_we0),
    .output0_we1(stage12_output0_we1),
    .output0_d0(stage12_output0_d0),
    .output0_d1(stage12_output0_d1)
  );

  _Z15yolo26n_stage13PKfPf u_stage13 (
    .clock(clock),
    .reset(reset),
    .start_port(stage_start[13]),
    .input0_q0(stage13_input0_q0),
    .input0_q1(stage13_input0_q1),
    .done_port(stage13_done),
    .input0_address0(stage13_input0_address0),
    .input0_address1(stage13_input0_address1),
    .input0_ce0(stage13_input0_ce0),
    .input0_ce1(stage13_input0_ce1),
    .output0_address0(stage13_output0_address0),
    .output0_address1(stage13_output0_address1),
    .output0_ce0(stage13_output0_ce0),
    .output0_ce1(stage13_output0_ce1),
    .output0_we0(stage13_output0_we0),
    .output0_we1(stage13_output0_we1),
    .output0_d0(stage13_output0_d0),
    .output0_d1(stage13_output0_d1)
  );

  _Z15yolo26n_stage14PKfPf u_stage14 (
    .clock(clock),
    .reset(reset),
    .start_port(stage_start[14]),
    .input0_q0(stage14_input0_q0),
    .input0_q1(stage14_input0_q1),
    .done_port(stage14_done),
    .input0_address0(stage14_input0_address0),
    .input0_address1(stage14_input0_address1),
    .input0_ce0(stage14_input0_ce0),
    .input0_ce1(stage14_input0_ce1),
    .output0_address0(stage14_output0_address0),
    .output0_address1(stage14_output0_address1),
    .output0_ce0(stage14_output0_ce0),
    .output0_ce1(stage14_output0_ce1),
    .output0_we0(stage14_output0_we0),
    .output0_we1(stage14_output0_we1),
    .output0_d0(stage14_output0_d0),
    .output0_d1(stage14_output0_d1)
  );

  _Z15yolo26n_stage15PKfS0_Pf u_stage15 (
    .clock(clock),
    .reset(reset),
    .start_port(stage_start[15]),
    .input0_q0(stage15_input0_q0),
    .input0_q1(stage15_input0_q1),
    .input1_q0(stage15_input1_q0),
    .input1_q1(stage15_input1_q1),
    .done_port(stage15_done),
    .input0_address0(stage15_input0_address0),
    .input0_address1(stage15_input0_address1),
    .input0_ce0(stage15_input0_ce0),
    .input0_ce1(stage15_input0_ce1),
    .input1_address0(stage15_input1_address0),
    .input1_address1(stage15_input1_address1),
    .input1_ce0(stage15_input1_ce0),
    .input1_ce1(stage15_input1_ce1),
    .output0_address0(stage15_output0_address0),
    .output0_address1(stage15_output0_address1),
    .output0_ce0(stage15_output0_ce0),
    .output0_ce1(stage15_output0_ce1),
    .output0_we0(stage15_output0_we0),
    .output0_we1(stage15_output0_we1),
    .output0_d0(stage15_output0_d0),
    .output0_d1(stage15_output0_d1)
  );

  _Z15yolo26n_stage16PKfPf u_stage16 (
    .clock(clock),
    .reset(reset),
    .start_port(stage_start[16]),
    .input0_q0(stage16_input0_q0),
    .input0_q1(stage16_input0_q1),
    .done_port(stage16_done),
    .input0_address0(stage16_input0_address0),
    .input0_address1(stage16_input0_address1),
    .input0_ce0(stage16_input0_ce0),
    .input0_ce1(stage16_input0_ce1),
    .output0_address0(stage16_output0_address0),
    .output0_address1(stage16_output0_address1),
    .output0_ce0(stage16_output0_ce0),
    .output0_ce1(stage16_output0_ce1),
    .output0_we0(stage16_output0_we0),
    .output0_we1(stage16_output0_we1),
    .output0_d0(stage16_output0_d0),
    .output0_d1(stage16_output0_d1)
  );

  _Z15yolo26n_stage17PKfPf u_stage17 (
    .clock(clock),
    .reset(reset),
    .start_port(stage_start[17]),
    .input0_q0(stage17_input0_q0),
    .input0_q1(stage17_input0_q1),
    .done_port(stage17_done),
    .input0_address0(stage17_input0_address0),
    .input0_address1(stage17_input0_address1),
    .input0_ce0(stage17_input0_ce0),
    .input0_ce1(stage17_input0_ce1),
    .output0_address0(stage17_output0_address0),
    .output0_address1(stage17_output0_address1),
    .output0_ce0(stage17_output0_ce0),
    .output0_ce1(stage17_output0_ce1),
    .output0_we0(stage17_output0_we0),
    .output0_we1(stage17_output0_we1),
    .output0_d0(stage17_output0_d0),
    .output0_d1(stage17_output0_d1)
  );

  _Z15yolo26n_stage18PKfS0_Pf u_stage18 (
    .clock(clock),
    .reset(reset),
    .start_port(stage_start[18]),
    .input0_q0(stage18_input0_q0),
    .input0_q1(stage18_input0_q1),
    .input1_q0(stage18_input1_q0),
    .input1_q1(stage18_input1_q1),
    .done_port(stage18_done),
    .input0_address0(stage18_input0_address0),
    .input0_address1(stage18_input0_address1),
    .input0_ce0(stage18_input0_ce0),
    .input0_ce1(stage18_input0_ce1),
    .input1_address0(stage18_input1_address0),
    .input1_address1(stage18_input1_address1),
    .input1_ce0(stage18_input1_ce0),
    .input1_ce1(stage18_input1_ce1),
    .output0_address0(stage18_output0_address0),
    .output0_address1(stage18_output0_address1),
    .output0_ce0(stage18_output0_ce0),
    .output0_ce1(stage18_output0_ce1),
    .output0_we0(stage18_output0_we0),
    .output0_we1(stage18_output0_we1),
    .output0_d0(stage18_output0_d0),
    .output0_d1(stage18_output0_d1)
  );

  _Z15yolo26n_stage19PKfPf u_stage19 (
    .clock(clock),
    .reset(reset),
    .start_port(stage_start[19]),
    .input0_q0(stage19_input0_q0),
    .input0_q1(stage19_input0_q1),
    .done_port(stage19_done),
    .input0_address0(stage19_input0_address0),
    .input0_address1(stage19_input0_address1),
    .input0_ce0(stage19_input0_ce0),
    .input0_ce1(stage19_input0_ce1),
    .output0_address0(stage19_output0_address0),
    .output0_address1(stage19_output0_address1),
    .output0_ce0(stage19_output0_ce0),
    .output0_ce1(stage19_output0_ce1),
    .output0_we0(stage19_output0_we0),
    .output0_we1(stage19_output0_we1),
    .output0_d0(stage19_output0_d0),
    .output0_d1(stage19_output0_d1)
  );

  _Z15yolo26n_stage20PKfPf u_stage20 (
    .clock(clock),
    .reset(reset),
    .start_port(stage_start[20]),
    .input0_q0(stage20_input0_q0),
    .input0_q1(stage20_input0_q1),
    .done_port(stage20_done),
    .input0_address0(stage20_input0_address0),
    .input0_address1(stage20_input0_address1),
    .input0_ce0(stage20_input0_ce0),
    .input0_ce1(stage20_input0_ce1),
    .output0_address0(stage20_output0_address0),
    .output0_address1(stage20_output0_address1),
    .output0_ce0(stage20_output0_ce0),
    .output0_ce1(stage20_output0_ce1),
    .output0_we0(stage20_output0_we0),
    .output0_we1(stage20_output0_we1),
    .output0_d0(stage20_output0_d0),
    .output0_d1(stage20_output0_d1)
  );

  _Z15yolo26n_stage21PKfS0_Pf u_stage21 (
    .clock(clock),
    .reset(reset),
    .start_port(stage_start[21]),
    .input0_q0(stage21_input0_q0),
    .input0_q1(stage21_input0_q1),
    .input1_q0(stage21_input1_q0),
    .input1_q1(stage21_input1_q1),
    .done_port(stage21_done),
    .input0_address0(stage21_input0_address0),
    .input0_address1(stage21_input0_address1),
    .input0_ce0(stage21_input0_ce0),
    .input0_ce1(stage21_input0_ce1),
    .input1_address0(stage21_input1_address0),
    .input1_address1(stage21_input1_address1),
    .input1_ce0(stage21_input1_ce0),
    .input1_ce1(stage21_input1_ce1),
    .output0_address0(stage21_output0_address0),
    .output0_address1(stage21_output0_address1),
    .output0_ce0(stage21_output0_ce0),
    .output0_ce1(stage21_output0_ce1),
    .output0_we0(stage21_output0_we0),
    .output0_we1(stage21_output0_we1),
    .output0_d0(stage21_output0_d0),
    .output0_d1(stage21_output0_d1)
  );

  _Z15yolo26n_stage22PKfPf u_stage22 (
    .clock(clock),
    .reset(reset),
    .start_port(stage_start[22]),
    .input0_q0(stage22_input0_q0),
    .input0_q1(stage22_input0_q1),
    .done_port(stage22_done),
    .input0_address0(stage22_input0_address0),
    .input0_address1(stage22_input0_address1),
    .input0_ce0(stage22_input0_ce0),
    .input0_ce1(stage22_input0_ce1),
    .output0_address0(stage22_output0_address0),
    .output0_address1(stage22_output0_address1),
    .output0_ce0(stage22_output0_ce0),
    .output0_ce1(stage22_output0_ce1),
    .output0_we0(stage22_output0_we0),
    .output0_we1(stage22_output0_we1),
    .output0_d0(stage22_output0_d0),
    .output0_d1(stage22_output0_d1)
  );

  _Z15yolo26n_stage23PKfS0_S0_Pf u_stage23 (
    .clock(clock),
    .reset(reset),
    .start_port(stage_start[23]),
    .input0_q0(stage23_input0_q0),
    .input0_q1(stage23_input0_q1),
    .input1_q0(stage23_input1_q0),
    .input1_q1(stage23_input1_q1),
    .input2_q0(stage23_input2_q0),
    .input2_q1(stage23_input2_q1),
    .done_port(stage23_done),
    .input0_address0(stage23_input0_address0),
    .input0_address1(stage23_input0_address1),
    .input0_ce0(stage23_input0_ce0),
    .input0_ce1(stage23_input0_ce1),
    .input1_address0(stage23_input1_address0),
    .input1_address1(stage23_input1_address1),
    .input1_ce0(stage23_input1_ce0),
    .input1_ce1(stage23_input1_ce1),
    .input2_address0(stage23_input2_address0),
    .input2_address1(stage23_input2_address1),
    .input2_ce0(stage23_input2_ce0),
    .input2_ce1(stage23_input2_ce1),
    .output0_address0(stage23_output0_address0),
    .output0_address1(stage23_output0_address1),
    .output0_ce0(stage23_output0_ce0),
    .output0_ce1(stage23_output0_ce1),
    .output0_we0(stage23_output0_we0),
    .output0_we1(stage23_output0_we1),
    .output0_d0(stage23_output0_d0),
    .output0_d1(stage23_output0_d1)
  );

endmodule
