// Generated by tools/generate_yolo26n_top_wrapper.py
module yolo26n_top_tb;
  reg clock;
  reg reset;
  reg start;
  wire done;
  wire busy;
  wire [4:0] current_stage;
  reg host_input_we;
  reg [20:0] host_input_addr;
  reg [31:0] host_input_data;
  reg [10:0] host_output_addr;
  wire [31:0] host_output_data;
  reg [31:0] expected_output [0:1799];
  reg [1023:0] input_hex_path;
  reg [1023:0] expected_hex_path;
  integer cycle_count;
  integer mismatch_count;
  integer i;
  reg busy_q;
  reg [4:0] current_stage_q;

  yolo26n_top dut (
    .clock(clock),
    .reset(reset),
    .start(start),
    .done(done),
    .busy(busy),
    .current_stage(current_stage),
    .host_input_we(host_input_we),
    .host_input_addr(host_input_addr),
    .host_input_data(host_input_data),
    .host_output_addr(host_output_addr),
    .host_output_data(host_output_data)
  );

  initial begin
    clock = 1'b0;
    forever #5 clock = ~clock;
  end

  initial begin
    host_input_we = 1'b0;
    host_input_addr = 21'd0;
    host_input_data = 32'd0;
    host_output_addr = 11'd0;
    reset = 1'b1;
    start = 1'b0;
    busy_q = 1'b0;
    current_stage_q = 5'd0;
    if (!$value$plusargs("INPUT_HEX=%s", input_hex_path)) begin
      input_hex_path = "rtl/yolo26n_top/testvectors/input_random.hex";
    end
    if (!$value$plusargs("EXPECTED_HEX=%s", expected_hex_path)) begin
      expected_hex_path = "rtl/yolo26n_top/testvectors/expected_random.hex";
    end
    $display("INFO loading input image from %0s", input_hex_path);
    $readmemh(input_hex_path, dut.u_mem_images.mem);
    $display("INFO loading expected output from %0s", expected_hex_path);
    $readmemh(expected_hex_path, expected_output);
    $display("INFO releasing reset");
    repeat (4) @(posedge clock);
    reset <= 1'b0;
    @(posedge clock);
    $display("INFO asserting start");
    start <= 1'b1;
    @(posedge clock);
    start <= 1'b0;
    cycle_count = 0;
    while (!done && cycle_count < 50000000) begin
      @(posedge clock);
      cycle_count = cycle_count + 1;
      if (busy && (!busy_q || (current_stage != current_stage_q))) begin
        $display("INFO cycle=%0d stage=%0d", cycle_count, current_stage);
      end
      if ((cycle_count % 100000) == 0) begin
        $display("INFO cycle=%0d busy=%0d stage=%0d done=%0d", cycle_count, busy, current_stage, done);
      end
      busy_q = busy;
      current_stage_q = current_stage;
    end
    if (!done) begin
      $display("TIMEOUT after %0d cycles at stage %0d", cycle_count, current_stage);
      $finish(2);
    end
    mismatch_count = 0;
    for (i = 0; i < 1800; i = i + 1) begin
      host_output_addr = i[10:0];
      #1;
      if (host_output_data !== expected_output[i]) begin
        if (mismatch_count < 8) begin
          $display("MISMATCH idx=%0d got=%h expected=%h", i, host_output_data, expected_output[i]);
        end
        mismatch_count = mismatch_count + 1;
      end
    end
    if (mismatch_count == 0) begin
      $display("PASS cycles=%0d", cycle_count);
    end else begin
      $display("FAIL mismatches=%0d", mismatch_count);
      $finish(3);
    end
    $finish(0);
  end
endmodule
